Adding 2nd example
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #100
Opened 2021-12-06 17:02 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/94

2021-12-06 17:03 UTC, opbld30 commented
Docs Build status updates of commit _[fe49e65](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/fe49e65ca677340cbe738b6239c3b9d0e2dc7444)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/revoke-spousersession?view=sharepoint-ps&branch=pr-en-us-100) (sharepoint-ps) | [Details](#user-content-a742bb7a5f62fb9e02d0ab70dc91ac7e-5063c1a4)

<a id="a742bb7a5f62fb9e02d0ab70dc91ac7e-5063c1a4"></a>
### [sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md)
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C6%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202112061702047766-100%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-06T17%3A03%3A28Z&sr=b&sp=r&sig=6o6%2FY2ZrUekP5mx9lBXw8vzXMFJfDJTDHsej1JslYh8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-06 18:52 UTC, tseward approved these changes

2021-12-07 08:55 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md
>  This example signs out user1 in the contoso tenancy from all devices.
```suggestion
This example signs out user1 in the Contoso tenancy from all devices.
```

2021-12-07 08:56 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md
> +This example signs out user1 in the contoso tenancy from all devices without prompting for confirmation.
```suggestion
This example signs out user1 in the Contoso tenancy from all devices without prompting for confirmation.  
```

2021-12-07 08:56 UTC, JohanFreelancer9 requested changes
Copy review.

2021-12-07 10:35 UTC, yogkumgit commented
@get-itips

2021-12-07 12:06 UTC, opbld32 commented
Docs Build status updates of commit _[31b0e0f](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/31b0e0fd79b2082c30ab34ec1410a4922584f06e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/revoke-spousersession?view=sharepoint-ps&branch=pr-en-us-100) (sharepoint-ps) | [Details](#user-content-a742bb7a5f62fb9e02d0ab70dc91ac7e-65a4b7b7)

<a id="a742bb7a5f62fb9e02d0ab70dc91ac7e-65a4b7b7"></a>
### [sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md)
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202112071205094026-100%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T12%3A06%3A20Z&sr=b&sp=r&sig=Q6ywAuyReyf6fBJLD7aazbPRMbbsWSQG824HT%2FsGvNE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 12:06 UTC, opbld31 commented
Docs Build status updates of commit _[6beb1a4](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/6beb1a4911c8cf0d2e3503c48c082e8c0c45f942)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/revoke-spousersession?view=sharepoint-ps&branch=pr-en-us-100) (sharepoint-ps) | [Details](#user-content-a742bb7a5f62fb9e02d0ab70dc91ac7e-462717e1)

<a id="a742bb7a5f62fb9e02d0ab70dc91ac7e-462717e1"></a>
### [sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md)
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C7%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202112071205151412-100%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-07T12%3A06%3A48Z&sr=b&sp=r&sig=tXMQAn8yf75NsRC3OUwqXVqgDQXkjf%2BWXbFbDL3Uujg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-07 12:10 UTC, JohanFreelancer9 approved these changes

2021-12-07 13:20 UTC, yogkumgit commented
@dariomws

2021-12-08 16:38 UTC, dariomws approved these changes

2021-12-09 05:55 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks.

2021-12-09 18:03 UTC, opbld30 commented
Docs Build status updates of commit _[964092d](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/964092d2188177535a25e33cf1dcc927145dbbde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/revoke-spousersession?view=sharepoint-ps&branch=pr-en-us-100) (sharepoint-ps) | [Details](#user-content-a742bb7a5f62fb9e02d0ab70dc91ac7e-9815dced)

<a id="a742bb7a5f62fb9e02d0ab70dc91ac7e-9815dced"></a>
### [sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md)
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 0, Column 0**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'user' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C9%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202112091801547509-100%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-09T18%3A03%3A21Z&sr=b&sp=r&sig=S9Eo46oV1xRGygMNKNoHnhQrFbr8DO1NuW5Tw9rTsNg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-09 18:03 UTC, merged