Add AllowMediaTranscription description
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #107
Opened 2021-12-15 00:36 UTC by mskaai

There is an updated value that allow for admins to manage transcription generation for all videos in ODSP. This will control the initial on demand feature allowing owners to request a transcript on demand as well as the longer term automatic transcription feature.

2021-12-15 00:38 UTC, opbld30 commented
Docs Build status updates of commit _[7072493](https://github.com/mskaai/OfficeDocs-SharePoint-PowerShell/commits/70724938e6113d7101420c3b512f67942d975a88)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/mskaai/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-107) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C15%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202112150036477544-107%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-15T00%3A38%3A10Z&sr=b&sp=r&sig=D0O7k8fuzjAg6gemiY5gYwJ16S%2Fpvfo%2F03j9XkQZ55Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-16 04:36 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2021-12-16 04:46 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +- False - Videos cannot have transcripts generated by Stream in any scenario. Note there are other scenarios where transcript could still exist.
```suggestion
- False - Videos cannot have transcripts generated by Stream in any scenario. Note that there are other scenarios where transcripts could still exist.  
```

2021-12-16 04:47 UTC, JohanFreelancer9 requested changes
Copy review - @mskaai, kindly commit the minor suggested change. Many thanks.

2021-12-16 05:54 UTC, opbld31 commented
Docs Build status updates of commit _[b6ddc32](https://github.com/mskaai/OfficeDocs-SharePoint-PowerShell/commits/b6ddc32dbd47676a88583f51637ab86348415e52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/mskaai/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-107) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C16%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202112160553205142-107%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-16T05%3A54%3A29Z&sr=b&sp=r&sig=MkKHsgrnzEqcmkHr9jINNmOmPiIYJyqj8J%2BE0N4XmtA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-12-16 06:21 UTC, JohanFreelancer9 approved these changes

2021-12-16 15:39 UTC, tseward approved these changes

2021-12-16 16:27 UTC, get-itips commented
Hello @mskaai 
Same question as https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/108#issuecomment-995946715

2021-12-17 12:49 UTC, yogkumgit commented
@mskaai Please update

2022-01-18 18:48 UTC, mskaai commented
> Collaborator

Hi, it should be published in version 16.0.21909.12000. This is also the old PR, I actually submitted an updated PR that went through I think.

2022-01-18 21:02 UTC, get-itips commented
> > Collaborator
> 
> Hi, it should be published in version 16.0.21909.12000. This is also the old PR, I actually submitted an updated PR that went through I think.

Do you mean the PR 108? It is for Set-SPOSite and this is for Set-SPOTenant, please confirm if this PR is still valid, thanks

2022-01-18 21:03 UTC, get-itips approved these changes

2022-01-18 21:09 UTC, dariomws approved these changes

2022-01-19 07:24 UTC, yogkumgit commented
@tiburd

2022-01-19 21:32 UTC, opbld30 commented
Docs Build status updates of commit _[b73a8ed](https://github.com/mskaai/OfficeDocs-SharePoint-PowerShell/commits/b73a8ed6ddedaa4e8e2e44a81a478316c6337d14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/mskaai/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-107) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202201192130332159-107%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T21%3A32%3A16Z&sr=b&sp=r&sig=ex1ZZJLcDNr4Q6FUE%2BlUJY0XE3bF6n7FfhZ5MkhfwrY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-19 21:32 UTC, merged