Create Stop-SPOTenantRename
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #13
Opened 2021-09-09 21:51 UTC by WayneEwington

Documenting the new PowerShell cmdlets to support SPO Tenant Renames.

Please include this PR with the other files:
* Start-SPOTenantRename
* Get-SPOTenantRenameStatus
* Stop-SPOTenantRename

2021-10-04 17:46 UTC, WayneEwington commented
@yogkumgit  How long is it expected for JohanFreelancer9 to do the review as this article needs to be published. (Also note that I can't @mention him.)

2021-10-05 12:53 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Stop-SPOTenantRename
> +---
I think that when you copied the content all of the above wasn't intended.

2021-10-05 12:54 UTC, get-itips requested changes
@WayneEwington please rename the file adding the ".md" extension

2021-10-05 12:55 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Stop-SPOTenantRename
> +Parameter Sets: Default
```suggestion
Parameter Sets: (All)
```

2021-10-05 12:55 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Stop-SPOTenantRename
> +Parameter Sets: Default
```suggestion
Parameter Sets: (All)
```

2021-10-05 12:56 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Stop-SPOTenantRename
> +[Get-SPOSiteRenameState](Get-TenantSiteState.md)
this should be the end of the file, the following text wasn't probably intended to be included.

2021-10-06 09:12 UTC, dariomws commented on sharepoint/sharepoint-ps/sharepoint-online/Stop-SPOTenantRename
> + [!IMPORTANT]
```suggestion
 [!IMPORTANT]
```

Same as https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/11 and https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/12.

2021-10-06 11:22 UTC, yogkumgit commented
@WayneEwington Please implement the suggested changes, if you agree. Thanks

2021-10-06 18:28 UTC, closed without merging