Adjust description and add example
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #135
Opened 2022-01-19 23:20 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/132

2022-01-19 23:22 UTC, opbld33 commented
Docs Build status updates of commit _[3791d33](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/3791d33723101e40f5b0c144050e294dc148ad95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-7/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps&branch=pr-en-us-135) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C19%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202201192320556691-135%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-19T23%3A22%3A42Z&sr=b&sp=r&sig=GqpBMbr6sWPRbpIQbxfpBW1AdOy%2B1apW6PHKjji7X0U%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-20 06:36 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-20 07:36 UTC, JohanFreelancer9 approved these changes

2022-01-20 09:31 UTC, dariomws approved these changes
Should we keep the note formatted?

2022-01-20 13:29 UTC, get-itips commented
> Should we keep the note formatted?

What's the last directive about that?

2022-01-20 19:01 UTC, tseward approved these changes

2022-01-21 04:06 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md
>  > [!NOTE]
```suggestion
```

2022-01-21 04:07 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md
> +> The ITAR value is for GCC High and DoD tenancies only.
```suggestion
**Note**: The ITAR value is for GCC High and DoD tenancies only.
```

2022-01-21 04:09 UTC, JohanFreelancer9 requested changes
@dariomws, that is a valid question. @get-itips, because PowerShell does not support markdown, I suggest changing the format, please.

2022-01-21 14:24 UTC, get-itips commented
> @dariomws, that is a valid question. @get-itips, because PowerShell does not support markdown, I suggest changing the format, please.

Certainly, but lately we've been accepting it in other PRs

Will change it :)

2022-01-21 14:26 UTC, opbld32 commented
Docs Build status updates of commit _[264d1f6](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/264d1f63dceb81585c8c8339ecdee59fd000cb21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-7/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps&branch=pr-en-us-135) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202201211425075633-135%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T14%3A26%3A49Z&sr=b&sp=r&sig=bVo46ecMKHkgpUunB1SPBElY8c3x%2BmZrA8cwzl2qU6Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 14:28 UTC, opbld32 commented
Docs Build status updates of commit _[ebcbc02](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/ebcbc02fe0b7ea504bdfe0c8e565c4331c85075a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-7/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps&branch=pr-en-us-135) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C21%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202201211425363110-135%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-21T14%3A28%3A43Z&sr=b&sp=r&sig=9eB7mjjbxvHHCs0Pk7Xj0Xe1aBtLgTbuVw57Eh5McR0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-21 14:42 UTC, dariomws commented
@get-itips, it's a good question. Actually, I think the directive is not to use formatted notes on the office-docs-powershell repo.

2022-01-22 09:33 UTC, JohanFreelancer9 approved these changes

2022-01-24 06:52 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-01-24 17:47 UTC, opbld32 commented
Docs Build status updates of commit _[c4e262f](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/c4e262fd3bd0cd0b394ed99c5ba95b71d9e43bf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-7/sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps&branch=pr-en-us-135) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C24%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202201241745438236-135%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-24T17%3A47%3A21Z&sr=b&sp=r&sig=lP3MPqe6A4R2iLkbq7QwJPu%2B6MNAR%2BySqljXHwlfNds%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-24 18:14 UTC, tiburd commented
@get-itips @dariomws @tseward @JohanFreelancer9 
Hi! 

Our admin, Thomas, said that alerts work in the repo when they are outside of the Synopsis section. I'll attend the PowerShell open office hours on Thursday to get complete guidance. I'll let you know and will update the wiki after that.

Thanks!

2022-01-24 18:14 UTC, merged