Update Get-PnPWebPart.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #142
Opened 2022-01-26 19:12 UTC by russgove

only returns webparts from classic pages

2022-01-26 19:17 UTC, opbld32 commented
Docs Build status updates of commit _[6278ec4](https://github.com/russgove/OfficeDocs-SharePoint-PowerShell/commits/6278ec440b9793fea0b3ffa5d2e760d798833eda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWebPart.md](https://github.com/russgove/OfficeDocs-SharePoint-PowerShell/blob/patch-2/sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWebPart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpwebpart?view=sharepoint-ps&branch=pr-en-us-142) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C26%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202201261914307569-142%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-26T19%3A17%3A03Z&sr=b&sp=r&sig=Fcwo9%2FwsUJ0Xd6ji8jQ12ern7Hjeb6JPdJWrPsMRukQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-27 07:44 UTC, yogkumgit commented
@JohanFreelancer9 - kindly do the copy editor review for this PR. Thanks

2022-01-27 09:14 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWebPart.md
> +> This command only returns webparts from Classic Pages
```suggestion
>
> This command only returns webparts from Classic Pages.
```

2022-01-27 09:17 UTC, JohanFreelancer9 requested changes
Copy review - @russgove, kindly commit the suggested changes. Many thanks.

2022-01-27 10:45 UTC, dariomws requested changes

2022-01-27 10:45 UTC, dariomws commented on sharepoint/sharepoint-ps/sharepoint-pnp/Get-PnPWebPart.md
> +> This command only returns webparts from Classic Pages
```suggestion
> This command only returns webparts from classic pages.
```

2022-01-27 13:25 UTC, get-itips commented
how are you?

Even though the PnP documentation articles are on this repository, I need to kindly redirect you to open PnP cmdlets issues/pull requests [here](https://github.com/PnP/PowerShell/), in that repository, where a member of the PnP community will be able to correct the article/review your PR with your feedback.

**The documentation for PnP cmdlets is then synced from that repo into this one.**

Thank you!

cc @yogkumgit

2022-01-27 14:51 UTC, tseward commented
Closing issue as this change needs to be proposed elsewhere. @yogkumgit

2022-01-27 14:51 UTC, closed without merging