Updated landing page
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #144
Opened 2022-01-28 12:34 UTC by erwinvanhunen

Updated landing page to include correct terms and cmdlets to install and update PnP PowerShell

2022-01-28 12:36 UTC, opbld31 commented
Docs Build status updates of commit _[d2dd135](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/commits/d2dd1351b8167db6871f98ae642f1fd24bfe71bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?branch=pr-en-us-144) | [Details](#user-content-22bbd25646d0b0799a769c5a05bba5b6-b2582026)

<a id="22bbd25646d0b0799a769c5a05bba5b6-b2582026"></a>
### [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202201281234313141-144%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T12%3A36%3A08Z&sr=b&sp=r&sig=2hz8nKpKutCg9X2p8qUBPasxrVVbo6fMTdZZO6ddI8g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-28 12:39 UTC, opbld31 commented
Docs Build status updates of commit _[8617954](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/commits/861795442f46e905d5784be7a77fd6786611e979)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?branch=pr-en-us-144) | [Details](#user-content-22bbd25646d0b0799a769c5a05bba5b6-b8cd8f94)

<a id="22bbd25646d0b0799a769c5a05bba5b6-b8cd8f94"></a>
### [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C28%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202201281237338042-144%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-28T12%3A39%3A27Z&sr=b&sp=r&sig=AB9B691aVB96LFpde6oI5oLrFcU4axlKnKWpEJL6Dto%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-31 05:29 UTC, yogkumgit commented
@get-itips

2022-01-31 11:49 UTC, get-itips commented
@yogkumgit This one comes from a PnP maintainer so it is ok to merge.

2022-01-31 11:49 UTC, get-itips approved these changes

2022-02-01 04:32 UTC, yogkumgit commented
@dariomws @tseward

2022-02-01 06:13 UTC, tseward commented
@erwinvanhunen Given we can still use the older 2013-2019 cmdlets and they may be actively used, can we document these 'legacy' cmdets in some other fashion?

Looping in @TroyStarr  as I don't want to see PnP cmdlet support documentation be lost on downlevel versions of SharePoint Server.

2022-02-01 06:21 UTC, JohanFreelancer9 commented on sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md
> +See this [page](https://pnp.github.io/powershell/) for more information on how to use PnP PowerShell and setup various things like the use of a Credential Manager.
```suggestion
See this [page](https://pnp.github.io/powershell/) for more information on how to use PnP PowerShell and to set up various things like the use of a Credential Manager.
```

2022-02-01 06:24 UTC, JohanFreelancer9 requested changes
Copy review - @erwinvanhunen, kindly commit the minor suggested change. Many thanks.

2022-02-02 20:18 UTC, opbld30 commented
Docs Build status updates of commit _[5a60ed5](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/commits/5a60ed56594423bf5b15c59af3888c26959d2b0e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?branch=pr-en-us-144) | [Details](#user-content-22bbd25646d0b0799a769c5a05bba5b6-2e050312)

<a id="22bbd25646d0b0799a769c5a05bba5b6-2e050312"></a>
### [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C2%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202022017002159-144%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-05T20%3A18%3A41Z&sr=b&sp=r&sig=01MrvsbImwhEnYt7llA1SSFdoNqkKIHpz%2BWKDBFRoEM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-03 14:04 UTC, JohanFreelancer9 approved these changes

2022-02-08 12:16 UTC, yogkumgit commented
@erwinvanhunen Thanks

2022-02-11 12:15 UTC, yogkumgit commented
@erwinvanhunen Gentle reminder

2022-02-11 16:49 UTC, tseward approved these changes

2022-02-15 12:05 UTC, yogkumgit commented
@dariomws

2022-02-15 15:15 UTC, yogkumgit commented
@tiburd

2022-02-15 18:32 UTC, opbld32 commented
Docs Build status updates of commit _[6ddc65d](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/commits/6ddc65dd99894b3abf43dc9ac5193ca6652e92dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?branch=pr-en-us-144) | [Details](#user-content-22bbd25646d0b0799a769c5a05bba5b6-8bab4d00)

<a id="22bbd25646d0b0799a769c5a05bba5b6-8bab4d00"></a>
### [sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202151830498573-144%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T18%3A32%3A49Z&sr=b&sp=r&sig=Orb3lgFId%2Blg49X9nnYMx1eSy6O9XUdcBcCIsB4bJYE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 19:41 UTC, opbld30 commented
Docs Build status updates of commit _[89254f0](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/commits/89254f098256b861dec9fc03baafd71ff4652a92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?branch=pr-en-us-144) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202151940075485-144%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T19%3A41%3A50Z&sr=b&sp=r&sig=3aSI%2BiaZLDehtWZ5dUfrLmARmipZbyMWEEvW2IdtGqQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 19:43 UTC, opbld33 commented
Docs Build status updates of commit _[29ad200](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/commits/29ad2005840bfc468ff8d5ed8eff0fd8e6668199)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md](https://github.com/erwinvanhunen/OfficeDocs-SharePoint-PowerShell/blob/PnP20220128/sharepoint/docs-conceptual/sharepoint-pnp/sharepoint-pnp-cmdlets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-pnp/sharepoint-pnp-cmdlets?branch=pr-en-us-144) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202151941261451-144%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T19%3A43%3A37Z&sr=b&sp=r&sig=rKXtB4uTXcD%2BuMV2erB7WQjd5oC3CLR%2FUfdqDxeodUo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 19:43 UTC, merged