Update Update-SPODataEncryptionPolicy.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #147
Opened 2022-02-01 20:05 UTC by sathana87

2022-02-01 20:08 UTC, opbld30 commented
Docs Build status updates of commit _[bfa962e](https://github.com/sathana87/OfficeDocs-SharePoint-PowerShell/commits/bfa962e38f1bf6eb583905a12908bd41d0774578)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md](https://github.com/sathana87/OfficeDocs-SharePoint-PowerShell/blob/patch-2/sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/update-spodataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-147) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C1%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202012006466807-147%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-04T20%3A08%3A29Z&sr=b&sp=r&sig=T%2BKMGvGvoqTRTNLBY2KRGHJ2ODS8siKl316%2Fpb85FKo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-02 05:54 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-02-02 12:04 UTC, dariomws approved these changes

2022-02-02 12:04 UTC, dariomws commented on sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md
> +Use the Update -SPODataEncryptionPolicy cmdlet to update customer encryption status for your geo tenant.
```suggestion
Use the Update-SPODataEncryptionPolicy cmdlet to update customer encryption status for your geo tenant.
```

2022-02-02 13:57 UTC, JohanFreelancer9 approved these changes
Copy review - approved with @dariomw's suggested change implemented.

2022-02-03 18:08 UTC, tseward approved these changes
Also approved with @dariomw's changes.

2022-02-04 07:39 UTC, yogkumgit commented
@get-itips

2022-02-04 17:47 UTC, get-itips requested changes
I am ok once Dario's suggestion is applied

2022-02-07 05:17 UTC, yogkumgit commented
@sathana87 Please implement the suggested changes.

2022-02-10 08:41 UTC, yogkumgit commented
@sathana87 Gentle reminder.

2022-02-15 12:06 UTC, yogkumgit commented
@tiburd Please help.

2022-02-15 19:22 UTC, opbld32 commented
Docs Build status updates of commit _[9578400](https://github.com/sathana87/OfficeDocs-SharePoint-PowerShell/commits/9578400aad20562deddc9faa462dfd4ef78b2fc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md](https://github.com/sathana87/OfficeDocs-SharePoint-PowerShell/blob/patch-2/sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/update-spodataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-147) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202151920251765-147%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T19%3A22%3A02Z&sr=b&sp=r&sig=6ANaWNIsHrPhEVCVhdgWyfG3anHqQlBaJuu%2B1gIF0tA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 19:23 UTC, opbld32 commented
Docs Build status updates of commit _[c1c2203](https://github.com/sathana87/OfficeDocs-SharePoint-PowerShell/commits/c1c22031492e94dd85f13b1476bc5996a15338ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md](https://github.com/sathana87/OfficeDocs-SharePoint-PowerShell/blob/patch-2/sharepoint/sharepoint-ps/sharepoint-online/Update-SPODataEncryptionPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/update-spodataencryptionpolicy?view=sharepoint-ps&branch=pr-en-us-147) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C15%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202151920384628-147%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-18T19%3A23%3A41Z&sr=b&sp=r&sig=m45cZ2N2uIJ31p5Qqjuh8Rw1GfNmFtwCsdwlrvpYhac%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-15 19:26 UTC, merged