Remove the parameter: ResourceQuota
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #165
Opened 2022-02-23 06:35 UTC by Byronliu123

when I run the Powershell which includes Resource Quota parameter, the warning message: the parameter resourcequota is obsolete, so please remove it in the article.

2022-02-23 06:37 UTC, opbld32 commented
Docs Build status updates of commit _[9da1f78](https://github.com/Byronliu123/OfficeDocs-SharePoint-PowerShell/commits/9da1f78a02352f76f1501d971c7b791462f713ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md](https://github.com/Byronliu123/OfficeDocs-SharePoint-PowerShell/blob/patch-3/sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/new-sposite?view=sharepoint-ps&branch=pr-en-us-165) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202230635224344-165%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T06%3A37%3A02Z&sr=b&sp=r&sig=8qIKOywieaMqcKFArH4BGdcturCNI59Z%2FHLYsaSyu7k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 08:55 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md
```suggestion
```

2022-02-23 08:56 UTC, JohanFreelancer9 requested changes
Copy review - @Byronliu123, kindly commit the suggested change to remove the extra blank line. Many thanks.

2022-02-24 07:35 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-02-24 07:54 UTC, dariomws reviewed
Hi @Byronliu123, thank you for your contribution.

When a parameter is still in the code but deprecated, we don't remove it from the article. Instead, we detail in the description that the parameter was deprecated.

2022-02-24 12:57 UTC, get-itips requested changes
> Hi @Byronliu123, thank you for your contribution.
> 
> When a parameter is still in the code but deprecated, we don't remove it from the article. Instead, we detail in the description that the parameter was deprecated.

Agreed

2022-02-24 15:37 UTC, JohanFreelancer9 approved these changes

2022-02-25 11:09 UTC, yogkumgit commented
@Byronliu123 Gentle reminder.

2022-03-01 10:51 UTC, yogkumgit commented
@Byronliu123 Please implement the suggested feedback so that merge can be initiated. Thanks

2022-03-08 02:32 UTC, yogkumgit commented
@tiburd Please help.

2022-03-08 16:11 UTC, tiburd commented
Closing this PR based on reviewers' comments.

2022-03-08 16:11 UTC, closed without merging