Remove ResourceQuota parameter
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #166
Opened 2022-02-23 06:44 UTC by Byronliu123

I got the warning info: the parameter resourcequota is obsolete after I executed the powershell of Example2

2022-02-23 06:45 UTC, opbld32 commented
Docs Build status updates of commit _[34dec07](https://github.com/Byronliu123/OfficeDocs-SharePoint-PowerShell/commits/34dec07ba0fc59aec7470467466c4d3cfef91470)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/Byronliu123/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-166) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C2%5C23%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202202230644062301-166%5Cworkflow_report.html?sv=2020-08-04&se=2022-03-26T06%3A45%3A43Z&sr=b&sp=r&sig=IMW8ScASCMld9i3Ipy2TsLKDQCEhe0Q%2Bx4S7Z5bgpUY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-02-23 09:09 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
>  Example 2 updates the settings of site collection <https://contoso.sharepoint.com/sites/site1.> The storage quota is updated to 1024 megabytes (1 GB) and the resource quota is updated to 0 megabytes.
```suggestion
Example 2 updates the settings of site collection <https://contoso.sharepoint.com/sites/site1.> The storage quota is updated to 1024 megabytes (1 GB).
```

2022-02-23 09:09 UTC, JohanFreelancer9 requested changes
Copy review - @Byronliu123, kindly commit the suggested change. Many thanks.

2022-02-24 07:55 UTC, dariomws reviewed
Same comment as https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/165.

2022-02-24 13:31 UTC, yogkumgit commented
@Byronliu123 Please implement the suggested changes. Thanks

2022-02-25 11:09 UTC, yogkumgit commented
@Byronliu123 Gentle reminder.

2022-03-01 10:51 UTC, yogkumgit commented
@Byronliu123 Please implement the suggested feedback so that merge can be initiated. Thanks

2022-03-08 02:32 UTC, yogkumgit commented
@tiburd Please help.

2022-03-15 15:13 UTC, opbld31 commented
Docs Build status updates of commit _[124766a](https://github.com/Byronliu123/OfficeDocs-SharePoint-PowerShell/commits/124766a9b1a00e3c4efa6f8096dc1e0ac188d5d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/Byronliu123/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-166) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C15%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203151512192967-166%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-15T15%3A13%3A43Z&sr=b&sp=r&sig=5Ia1gkyhtZXKFuhPmCcEjiMBO0oT6pYZfcyWi%2FraWlo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-15 15:15 UTC, opbld31 commented
Docs Build status updates of commit _[84ba220](https://github.com/Byronliu123/OfficeDocs-SharePoint-PowerShell/commits/84ba220c86c645dbb9bfcbc3b53182686887f7d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/Byronliu123/OfficeDocs-SharePoint-PowerShell/blob/patch-4/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-166) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C15%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203151513086920-166%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-15T15%3A15%3A04Z&sr=b&sp=r&sig=VcpqoyMKzDtQf7WJYXV0pB6gH%2BksNkFIbI%2BcbtHuRkA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-15 15:17 UTC, merged