Update Set-SPOTenant.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #185
Opened 2022-03-11 20:40 UTC by SanjoyanM

2022-03-11 20:41 UTC, opbld33 commented
Docs Build status updates of commit _[3506922](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/commits/3506922267a44c30c91addc60897272b3fe8a171)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :x:Error | | [Details](#user-content-a3f83d4d494d30164090fd90611321b5-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingRule.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingRule.yml) | :warning:Warning | | [Details](#user-content-43d9e985a108b1d3fc3eb74126ed49db-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachinePool.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachinePool.yml) | :warning:Warning | | [Details](#user-content-eca838ffe6fa4fd3b4b5da85fb696e29-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachineInfo.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachineInfo.yml) | :warning:Warning | | [Details](#user-content-e71b023a1921d9f138c214b41892571e-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPScaleOutDatabase.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPScaleOutDatabase.yml) | :warning:Warning | | [Details](#user-content-d07f618f0966b6022bb70d07c2ea4c5f-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Add-FASTSearchResource.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-FASTSearchResource.yml) | :warning:Warning | | [Details](#user-content-040dab2b74238a5f3c147f175d8d7e5f-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Disable-SPAppAutoProvision.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Disable-SPAppAutoProvision.yml) | :warning:Warning | | [Details](#user-content-e83e84ec30f316af738e2b64104d06f4-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-online/index.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/index.yml) | :warning:Warning | | [Details](#user-content-a7936d3c0f84adc5050b8ac76259e00b-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.yml) | :warning:Warning | | [Details](#user-content-cb56e78956fe33121b165d5169ce3da8-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Copy-SPSite.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Copy-SPSite.yml) | :warning:Warning | | [Details](#user-content-b82cd1460324f4bde546b96f13a5bc71-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPServerScaleOutDatabase.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPServerScaleOutDatabase.yml) | :warning:Warning | | [Details](#user-content-3d65d5e5872b1647840f7ffc13f1dbb4-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Clear-SPBusinessDataCatalogEntityNotificationWeb.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Clear-SPBusinessDataCatalogEntityNotificationWeb.yml) | :warning:Warning | | [Details](#user-content-5f0c06c8082d48ff052313e22e7f8ebb-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Enable-SPAppAutoProvision.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Enable-SPAppAutoProvision.yml) | :warning:Warning | | [Details](#user-content-8b5b8cc768caaea7f9882506d9e607f3-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityLogLevel.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityLogLevel.yml) | :warning:Warning | | [Details](#user-content-0dabaea2eac360e98baa4cb54be50dad-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityCCTKServer.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityCCTKServer.yml) | :warning:Warning | | [Details](#user-content-0c17ddbf0908f316df9ad1ab4eb94f9d-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityClaimsUserStore.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityClaimsUserStore.yml) | :warning:Warning | | [Details](#user-content-5945a989f287046aad3a1d0ae297932a-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppDomain.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppDomain.yml) | :warning:Warning | | [Details](#user-content-cd5892d27adedf55d69d15194ada1d0c-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityPublicFilter.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityPublicFilter.yml) | :warning:Warning | | [Details](#user-content-3b3beada445dc9929e90c0ab435c43de-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityXMLAliaser.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityXMLAliaser.yml) | :warning:Warning | | [Details](#user-content-2b7b550c387f0ffcb61daa61bdd00179-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSearchSettingGroup.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSearchSettingGroup.yml) | :warning:Warning | | [Details](#user-content-fe2f7eb5cf0bc3f16c8081edabe16bec-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPUserLicenseMapping.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPUserLicenseMapping.yml) | :warning:Warning | | [Details](#user-content-996f8c2c95764aa0e460bca62ad8f1a3-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityAliaser.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityAliaser.yml) | :warning:Warning | | [Details](#user-content-9812a4d10971dbce56f6c08a072c1a71-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchResource.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchResource.yml) | :warning:Warning | | [Details](#user-content-16d767dd05c925c45234453d78a78b33-57a5cc7e)
[sharepoint/sharepoint-ps/sharepoint-server/Clear-SPServerScaleOutDatabaseDeletedDataSubRange.yml](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Clear-SPServerScaleOutDatabaseDeletedDataSubRange.yml) | :warning:Warning | | [Details](#user-content-6ec51ef597ded1bbe404398d3646dfed-57a5cc7e)
[sharepoint/sharepoint [...]

2022-03-11 20:45 UTC, opbld31 commented
Docs Build status updates of commit _[860027f](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/commits/860027faa0cc98e9d937749de7ea39a06f0f49d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/SanjoyanM/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-185) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C11%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203112044239276-185%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-11T20%3A45%3A54Z&sr=b&sp=r&sig=vwCwAPvRhZ2g2jXoOBeuv89qZOtQMwVY%2FMMMHesVsq4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-12 03:00 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-12 03:01 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-03-12 03:24 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Prevents apps using an ACS app-only access token to access SharePoint. Azure Access Control (ACS), a service of Azure Active Directory (Azure AD), has been retired on November 7, 2018. This retiremen
```suggestion
Prevents apps using an Azure Access Control (ACS) app-only access token to access SharePoint. ACS, a service of Azure Active Directory (Azure AD), has been retired on November 7, 2018. This retirement does not impact the SharePoint add-in model, which uses the https://accounts.accesscontrol.windows.net hostname (which is not impacted by this retirement). For new tenants, apps using an ACS app-only access token are disabled by default. We recommend using the Azure AD app-only model which is modern and more secure.
```

2022-03-12 03:33 UTC, JohanFreelancer9 requested changes
Copy review - @SanjoyanM, kindly commit the suggested changes. Many thanks.

2022-03-12 10:23 UTC, dariomws approved these changes

2022-03-12 12:58 UTC, get-itips approved these changes

2022-03-12 21:37 UTC, tseward approved these changes

2022-03-15 01:23 UTC, tseward approved these changes

2022-03-15 07:08 UTC, JohanFreelancer9 approved these changes

2022-03-15 14:29 UTC, merged