Update Set-SPOUser.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #195
Opened 2022-03-23 20:55 UTC by PowershellScripts

suggestion

2022-03-23 20:57 UTC, opbld30 commented
Docs Build status updates of commit _[a32e3e9](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/a32e3e938a26338be673429aa1229206a102fbad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps&branch=pr-en-us-195) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C23%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203232055331827-195%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-23T20%3A57%3A03Z&sr=b&sp=r&sig=bMZ0n8fQ8Kc9uVuoDDs710ACtXLX1lDO5rB5%2BEDdABM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-24 08:17 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md
> +If the UserType property of an existing user is changed in AzureAD from Member to Guest and vice-versa, this parameter can be used to update it in SharePoint Online.
```suggestion
If the UserType property of an existing user is changed in Azure AD from Member to Guest and vice-versa, this parameter can be used to update it in SharePoint Online.
```

2022-03-24 08:18 UTC, JohanFreelancer9 requested changes
Copy review - @PowershellScripts, kindly commit the minor additional suggested change. Many thanks.

2022-03-24 18:43 UTC, opbld30 commented
Docs Build status updates of commit _[97265fe](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/97265fe167a4c47dfe331ce9ffbe7754c35ae6fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps&branch=pr-en-us-195) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C24%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203241833193287-195%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-24T18%3A43%3A50Z&sr=b&sp=r&sig=kCRcSMnFWAbDdrU%2FNe8mwnTSCZI77KFHnDlHKIkma%2FY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-25 09:31 UTC, opbld31 commented
Docs Build status updates of commit _[7973682](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/7973682fba0d886448cf509d4387b20c13b7f167)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps&branch=pr-en-us-195) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C25%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203250930122470-195%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-25T09%3A31%3A41Z&sr=b&sp=r&sig=Omu7bShVnrpblp18UPDyOdkqxfNatQVL4U%2BTwOcOliY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-25 09:57 UTC, JohanFreelancer9 approved these changes

2022-03-25 13:42 UTC, get-itips approved these changes

2022-03-25 15:38 UTC, tseward requested changes

2022-03-25 15:38 UTC, tseward commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md
> +If the UserType property of an existing user is changed in Azure AD from Member to Guest and vice-versa, this parameter can be used to update it in SharePoint Online.
I would change this to "Guest or vice-versa,".

2022-03-25 22:23 UTC, dariomws approved these changes

2022-03-26 04:28 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md
> +If the UserType property of an existing user is changed in Azure AD from Member to Guest and vice-versa, this parameter can be used to update it in SharePoint Online.
```suggestion
If the UserType property of an existing user is changed in Azure AD from Member to Guest or vice-versa, this parameter can be used to update it in SharePoint Online.
```

2022-03-26 04:29 UTC, JohanFreelancer9 requested changes
@PowershellScripts, kindly commit the suggested change.

2022-03-26 20:29 UTC, opbld32 commented
Docs Build status updates of commit _[3aa4ab9](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/3aa4ab9a5125f3d79dd5d444e767a48492b618b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps&branch=pr-en-us-195) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C26%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203262027046060-195%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-26T20%3A29%3A22Z&sr=b&sp=r&sig=T8C3Lb%2FjbvowVvVDP2U82CjIfk0v9PsEjOD8utnlJVA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-28 05:54 UTC, JohanFreelancer9 approved these changes

2022-03-28 10:54 UTC, yogkumgit commented
@tseward

2022-03-28 17:23 UTC, opbld30 commented
Docs Build status updates of commit _[09c1a31](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/09c1a316f204803b96bc0235bfc50ceaf49e4b28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-11/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spouser?view=sharepoint-ps&branch=pr-en-us-195) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C28%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203281721391478-195%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-28T17%3A23%3A04Z&sr=b&sp=r&sig=23kjNHPSrHO6PTGbzwwDUmghuoo1bptP3r0rZQl8Zu0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-28 19:24 UTC, tseward approved these changes

2022-03-29 02:36 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-03-29 16:50 UTC, merged