Adding OneDriveLoopSharingCapability
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #204
Opened 2022-03-30 12:27 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/197

2022-03-30 12:28 UTC, opbld33 commented
Docs Build status updates of commit _[8638d3a](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/8638d3aa407984f2242c2b3021b52df87e4d707f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-12/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-204) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203301227359305-204%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T12%3A28%3A45Z&sr=b&sp=r&sig=yXMzrxXO3nC7gwJjQFTyE%2B9nDkGcook1sAtWM6LWI60%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 16:18 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-31 03:48 UTC, tseward approved these changes

2022-03-31 03:48 UTC, tseward commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +If you have the external sharing for ODB allowed, no further action is required. If you have external sharing disabled, you can leave it disabled but you must enable this new setting. For more inform
Please remove 'en-us'

2022-03-31 11:24 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +If you have the external sharing for ODB allowed, no further action is required. If you have external sharing disabled, you can leave it disabled but you must enable this new setting. For more inform
```suggestion
If you have the external sharing for ODB allowed, no further action is required. If you have external sharing disabled, you can leave it disabled but you must enable this new setting. For more information, see [Enable Microsoft Whiteboard for your organization](https://support.microsoft.com/office/enable-microsoft-whiteboard-for-your-organization-1caaa2e2-5c18-4bdf-b878-2d98f1da4b24).
```

2022-03-31 11:25 UTC, JohanFreelancer9 requested changes
Copy review.

2022-03-31 12:02 UTC, opbld32 commented
Docs Build status updates of commit _[2f0913f](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/2f0913f661d7919de08692525aa271ba72bd2ffe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-12/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-204) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203311200401574-204%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T12%3A02%3A08Z&sr=b&sp=r&sig=PcqlQLaPxh6fI4b4zxynek4x9NQS1bPlARl7ous%2FOvg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 12:13 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-31 14:42 UTC, JohanFreelancer9 approved these changes

2022-04-01 10:41 UTC, yogkumgit commented
@dariomws

2022-04-04 18:28 UTC, dariomws approved these changes

2022-04-05 18:40 UTC, opbld33 commented
Docs Build status updates of commit _[b52fa6e](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/b52fa6e88b754868b98d9259d47631a6ccdf7cfd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-12/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-204) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204051838559606-204%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T18%3A40%3A30Z&sr=b&sp=r&sig=%2B5Q6%2B0YpkFL0MsyAvDja7YJauY0bttvxiLg64Dk6RVM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 18:40 UTC, merged