Add option ShowOpenInDesktopOptionForSyncedFiles documentation to the Set-SPOTenant cmdlet
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #208
Opened 2022-03-30 23:09 UTC by osarguel

2022-03-30 23:10 UTC, opbld32 commented
Docs Build status updates of commit _[7beb861](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/7beb861f74aa9b15cf44faed932770c44634de92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203302309161218-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T23%3A10%3A34Z&sr=b&sp=r&sig=D%2FSJqy3S77gsN2F%2BN8YfLANZW%2FZlzQiLHPAdT2uDTpw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 23:11 UTC, opbld30 commented
Docs Build status updates of commit _[7beb861](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/7beb861f74aa9b15cf44faed932770c44634de92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203302310041232-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T23%3A11%3A45Z&sr=b&sp=r&sig=ZpW9A0XON0QHIIz3ZrStRvLvjNIrxCVWdGJZoRrSEhk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-31 12:16 UTC, yogkumgit commented
@JohanFreelancer9

2022-03-31 21:51 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +The valid values are:
>   [](http://example.com/codeflow?start=21&length=2)

Remove trailing spaces (here and a few places)

2022-03-31 21:53 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +- False (default) – Open In Desktop is disabled and the option is not shown in the file context menu.
>Open In Desktop [](http://example.com/codeflow?start=20&length=15)

should probably be "Open in desktop"

2022-03-31 22:21 UTC, opbld32 commented
Docs Build status updates of commit _[c01df76](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/c01df76a66c2eba3fdd7a2937a8f8d5801bae55d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C31%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202203312220076616-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-01T22%3A21%3A19Z&sr=b&sp=r&sig=J6saJ2O6RkGQmQa4DSIItHazXWEupblUEJU8M7HWr5Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-01 09:05 UTC, JohanFreelancer9 approved these changes

2022-04-01 10:46 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-04-01 15:27 UTC, tseward approved these changes

2022-04-01 22:19 UTC, opbld32 commented
Docs Build status updates of commit _[f626095](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/f6260951b2dc3fbc28161d1a4343a2cb47d500b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204012218164480-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T22%3A19%3A29Z&sr=b&sp=r&sig=AOJQ8OZN8%2B1nCkSghcQxnIxoANs%2FYhyjXU0mTpvQ%2B7E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 00:56 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +The ShowOpenInDesktopOptionForSyncedFiles setting (set to false by default) displays the “Open in desktop” option when users go to SharePoint or OneDrive on the web and open the shortcut menu for a f
retype these quotes so they're just `"`

here and other places.

2022-04-02 02:40 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +The ShowOpenInDesktopOptionForSyncedFiles setting (set to false by default) displays the “Open in desktop” option when users go to SharePoint or OneDrive on the web and open the shortcut menu for a f
```suggestion
The ShowOpenInDesktopOptionForSyncedFiles setting (set to false by default) displays the "Open in desktop" option when users go to SharePoint or OneDrive on the web and open the shortcut menu for a file that they’re syncing with the OneDrive sync app.
```

2022-04-02 02:41 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +- True – “Open in desktop” is enabled and the option to open synced files locally appears on the shortcut menu.
```suggestion
- False (default) – "Open in desktop" is disabled and not shown on the shortcut menu.
- True – "Open in desktop" is enabled and the option to open synced files locally appears on the shortcut menu.
```

2022-04-02 02:42 UTC, JohanFreelancer9 requested changes
@osarguel, kindly commit the suggested changes. Many thanks.

2022-04-04 16:49 UTC, opbld32 commented
Docs Build status updates of commit _[099675b](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/099675b7639d0e6bcbce62ee8e0c0378c966ac39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204041646587727-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T16%3A49%3A24Z&sr=b&sp=r&sig=2AOq3DyFaVdUCpa4qtD35WHWMrMzu2tsr10ecWEeLtg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-04 16:51 UTC, opbld31 commented
Docs Build status updates of commit _[063ada9](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/063ada928932c0140bcad18e6a005ef102d7ff1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204041650215348-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T16%3A51%3A32Z&sr=b&sp=r&sig=MgI0OzKUgUVnB8zZjRHF7QFSprQJxyf%2BdMWxQdgv48E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-04 17:32 UTC, samkabue approved these changes

2022-04-04 18:24 UTC, dariomws approved these changes

2022-04-04 20:17 UTC, get-itips approved these changes

2022-04-04 20:19 UTC, get-itips reviewed
Checked in 16.0.22315.12000 and it is not there yet, is this going in the next release? thank you

2022-04-05 09:32 UTC, JohanFreelancer9 approved these changes

2022-04-05 13:12 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-06 00:36 UTC, get-itips commented
> Checked in 16.0.22315.12000 and it is not there yet, is this going in the next release? thank you

@osarguel

2022-04-06 00:42 UTC, osarguel commented
> > Checked in 16.0.22315.12000 and it is not there yet, is this going in the next release? thank you
> 
> @osarguel

@samkabue  can you help me answering this?

2022-04-06 03:26 UTC, samkabue commented
@osarguel this is not available in current versions, but should be in the release coming out next.

2022-04-06 17:25 UTC, opbld31 commented
Docs Build status updates of commit _[3b2748e](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/3b2748e83ace778648c53c61f09e6ff1608d178e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :x:Error | | [Details](#user-content-a3f83d4d494d30164090fd90611321b5-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-online/index.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/index.yml) | :warning:Warning | | [Details](#user-content-a7936d3c0f84adc5050b8ac76259e00b-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.yml) | :warning:Warning | | [Details](#user-content-cb56e78956fe33121b165d5169ce3da8-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPAppDeniedEndpoint.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPAppDeniedEndpoint.yml) | :warning:Warning | | [Details](#user-content-7c7ccd89a59da73abf74c1e34f394dea-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Clear-SPBusinessDataCatalogEntityNotificationWeb.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Clear-SPBusinessDataCatalogEntityNotificationWeb.yml) | :warning:Warning | | [Details](#user-content-5f0c06c8082d48ff052313e22e7f8ebb-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Clear-SPScaleOutDatabaseDeletedDataSubRange.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Clear-SPScaleOutDatabaseDeletedDataSubRange.yml) | :warning:Warning | | [Details](#user-content-5101b47e699bffade94fdd6f364f06cd-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPDistributedCacheServiceInstance.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPDistributedCacheServiceInstance.yml) | :warning:Warning | | [Details](#user-content-2dd28ae5e02bb3472aa0cf7da3315ee4-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachineInfo.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachineInfo.yml) | :warning:Warning | | [Details](#user-content-e71b023a1921d9f138c214b41892571e-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Clear-SPServerScaleOutDatabaseDeletedDataSubRange.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Clear-SPServerScaleOutDatabaseDeletedDataSubRange.yml) | :warning:Warning | | [Details](#user-content-6ec51ef597ded1bbe404398d3646dfed-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Copy-SPSite.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Copy-SPSite.yml) | :warning:Warning | | [Details](#user-content-b82cd1460324f4bde546b96f13a5bc71-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Export-SPEnterpriseSearchTopology.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Export-SPEnterpriseSearchTopology.yml) | :warning:Warning | | [Details](#user-content-988416cdfef9298c5cffb874c82f66ad-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityLotusNotesUserStore.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityLotusNotesUserStore.yml) | :warning:Warning | | [Details](#user-content-8a37ba70848f36d24a4104c0dcf2540f-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataFullTextIndex.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataFullTextIndex.yml) | :warning:Warning | | [Details](#user-content-df48b8ed7404ad17d172bb51f29d42c5-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Enable-SPAppAutoProvision.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Enable-SPAppAutoProvision.yml) | :warning:Warning | | [Details](#user-content-8b5b8cc768caaea7f9882506d9e607f3-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Export-SPAppPackage.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Export-SPAppPackage.yml) | :warning:Warning | | [Details](#user-content-47676a145e98054451822b9dd1d48034-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataFullTextIndexMapping.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataFullTextIndexMapping.yml) | :warning:Warning | | [Details](#user-content-ec0e7f9d76fa6c7a69fb16085a681f70-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSpelltuningStatus.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSpelltuningStatus.yml) | :warning:Warning | | [Details](#user-content-5d6dc9aec28f42d6ac135a374bd26239-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Disable-SPAppAutoProvision.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Disable-SPAppAutoProvision.yml) | :warning:Warning | | [Details](#user-content-e83e84ec30f316af738e2b64104d06f4-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityRegexAliaser.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityRegexAliaser.yml) | :warning:Warning | | [Details](#user-content-740d23c016d146fc4310c31ee66906ea-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-SPAuthenticationRealm.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-SPAuthenticationRealm.yml) | :warning:Warning | | [Details](#user-content-0688be078cdd4a50f00975097bde6f6f-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppAutoProvisionConnection.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppAutoProvisionConnection.yml) | :warning:Warning | | [Details](#user-content-b999c6b7f8cf8659968ca4733dfe8242-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityCCTKServer.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityCCTKServer.yml) | :warning:Warning | | [Details](#user-content-0c17ddbf0908f316df9ad1ab4eb94f9d-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-SPBingMapsBlock.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-SPBingMapsBlock.yml) | :warning:Warning | | [Details](#user-content-ad0362018626d7bd7c38c8bc2c0c4c4c-6430cab2)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataCrawledPropertyMapping.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FAS [...]

2022-04-06 17:38 UTC, opbld30 commented
Docs Build status updates of commit _[9096d75](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/9096d75629d0ce49a33e77f4d6f03f11663f21b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204061736540119-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T17%3A38%3A29Z&sr=b&sp=r&sig=XQd5XZJKZPmrmeIw6APCtFmFstmwjZRr7dtuW3xq%2B5E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 17:48 UTC, tiburd commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Accept pipeline input: FalseAccept wildcard characters: False
```suggestion
Accept pipeline input: FalseAccept
Wildcard characters: False
```

2022-04-06 17:50 UTC, opbld33 commented
Docs Build status updates of commit _[e94dccc](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/e94dccc0c3c3cf43aa9d8ac5cb8a613b736b0aaf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :x:Error | | [Details](#user-content-a3f83d4d494d30164090fd90611321b5-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-online/index.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/index.yml) | :warning:Warning | | [Details](#user-content-a7936d3c0f84adc5050b8ac76259e00b-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachineInfo.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachineInfo.yml) | :warning:Warning | | [Details](#user-content-e71b023a1921d9f138c214b41892571e-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPDistributedCacheServiceInstance.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPDistributedCacheServiceInstance.yml) | :warning:Warning | | [Details](#user-content-2dd28ae5e02bb3472aa0cf7da3315ee4-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Add-FASTSearchResource.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-FASTSearchResource.yml) | :warning:Warning | | [Details](#user-content-040dab2b74238a5f3c147f175d8d7e5f-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingRule.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingRule.yml) | :warning:Warning | | [Details](#user-content-43d9e985a108b1d3fc3eb74126ed49db-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPServerScaleOutDatabase.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPServerScaleOutDatabase.yml) | :warning:Warning | | [Details](#user-content-3d65d5e5872b1647840f7ffc13f1dbb4-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachinePool.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPRoutingMachinePool.yml) | :warning:Warning | | [Details](#user-content-eca838ffe6fa4fd3b4b5da85fb696e29-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Add-FASTSearchSpelltuning.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-FASTSearchSpelltuning.yml) | :warning:Warning | | [Details](#user-content-6c6b9332921f4e94ab75e3132a51e557-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Add-SPUserLicenseMapping.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Add-SPUserLicenseMapping.yml) | :warning:Warning | | [Details](#user-content-996f8c2c95764aa0e460bca62ad8f1a3-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Disable-SPAppAutoProvision.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Disable-SPAppAutoProvision.yml) | :warning:Warning | | [Details](#user-content-e83e84ec30f316af738e2b64104d06f4-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Disable-SPProjectActiveDirectoryEnterpriseResourcePoolSync.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Disable-SPProjectActiveDirectoryEnterpriseResourcePoolSync.yml) | :warning:Warning | | [Details](#user-content-04cc897c303470a709b52f7f05b42ade-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Clear-SPBusinessDataCatalogEntityNotificationWeb.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Clear-SPBusinessDataCatalogEntityNotificationWeb.yml) | :warning:Warning | | [Details](#user-content-5f0c06c8082d48ff052313e22e7f8ebb-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Clear-SPScaleOutDatabaseDeletedDataSubRange.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Clear-SPScaleOutDatabaseDeletedDataSubRange.yml) | :warning:Warning | | [Details](#user-content-5101b47e699bffade94fdd6f364f06cd-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Copy-SPSite.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Copy-SPSite.yml) | :warning:Warning | | [Details](#user-content-b82cd1460324f4bde546b96f13a5bc71-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityRegexAliaser.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityRegexAliaser.yml) | :warning:Warning | | [Details](#user-content-740d23c016d146fc4310c31ee66906ea-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataFullTextIndex.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataFullTextIndex.yml) | :warning:Warning | | [Details](#user-content-df48b8ed7404ad17d172bb51f29d42c5-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataManagedProperty.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataManagedProperty.yml) | :warning:Warning | | [Details](#user-content-d705fc4c42a8c2ea51ece47a1ab89373-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityXMLAliaser.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityXMLAliaser.yml) | :warning:Warning | | [Details](#user-content-2b7b550c387f0ffcb61daa61bdd00179-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityLotusNotesUserStore.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchSecurityLotusNotesUserStore.yml) | :warning:Warning | | [Details](#user-content-8a37ba70848f36d24a4104c0dcf2540f-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppInstance.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppInstance.yml) | :warning:Warning | | [Details](#user-content-a8047884855977eafef1ee4f7807180c-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppDisablingConfiguration.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-SPAppDisablingConfiguration.yml) | :warning:Warning | | [Details](#user-content-4ac03c728306fb1a280bac8621378ede-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-SPBingMapsBlock.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-SPBingMapsBlock.yml) | :warning:Warning | | [Details](#user-content-ad0362018626d7bd7c38c8bc2c0c4c4c-e8bc651b)
[sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataCrawledProperty.yml](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-server/Get-FASTSearchMetadataCrawle [...]

2022-04-06 18:05 UTC, opbld32 commented
Docs Build status updates of commit _[0e09250](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/0e0925023b55735aabaee7d082aeee20075c26a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204061804144450-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T18%3A05%3A30Z&sr=b&sp=r&sig=vMbwRNVLH5BxYX6jGw7xo22rfP%2FR3pmA7DULhmTjM8c%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 18:17 UTC, tiburd commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Accept pipeline input: FalseAccept
```suggestion
Accept pipeline input: False
```

2022-04-06 18:20 UTC, opbld32 commented
Docs Build status updates of commit _[564b032](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/commits/564b032acb02d4186c6acdc5ca401c56c6bdde9f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/osarguel/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-208) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204061818182946-208%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T18%3A20%3A10Z&sr=b&sp=r&sig=XVqjuxrRf31xPxUOk6xKUbc2bBqfQ4R9%2BqiReY6V%2Ftg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-06 18:23 UTC, merged