Update Get-SPOCrossGeoMovedUsers.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #210
Opened 2022-04-01 16:58 UTC by PowershellScripts

2022-04-01 16:59 UTC, opbld33 commented
Docs Build status updates of commit _[cfab710](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/cfab710169cfe2600618023468453415155cb883)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMovedUsers.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-17/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMovedUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spocrossgeomovedusers?view=sharepoint-ps&branch=pr-en-us-210) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204011658225363-210%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T16%3A59%3A41Z&sr=b&sp=r&sig=%2B41qPvjT%2FbbXvXI4IkD9QcrY2MmClYpxfe%2Ffex0qeOE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 12:00 UTC, yogkumgit commented
@JohanFreelancer9

2022-04-04 02:59 UTC, tseward approved these changes

2022-04-04 04:12 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMovedUsers.md
> +This cmdlet allows you to get the moved users out and in the current SPO Site. It requires a connection to a multi-geo tenant to run correctly. You must be a SharePoint Online administrator or Global
```suggestion
This cmdlet allows you to get the moved users out and in the current SPO Site. It requires a connection to a multi-geo tenant to run correctly. You must be a SharePoint Online Administrator or Global Administrator to get the moved users out and in the current SPO site.
```

2022-04-04 04:13 UTC, JohanFreelancer9 requested changes
Copy review - @PowershellScripts, kindly commit the minor suggested change. Many thanks.

2022-04-04 14:27 UTC, yogkumgit commented
@PowershellScripts

2022-04-04 18:43 UTC, dariomws approved these changes

2022-04-04 20:29 UTC, get-itips approved these changes

2022-04-05 09:35 UTC, JohanFreelancer9 approved these changes

2022-04-05 13:13 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-05 18:58 UTC, opbld33 commented
Docs Build status updates of commit _[09bd62d](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/09bd62d9c7280e6aaf864c180800f6d6a753a772)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMovedUsers.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-17/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMovedUsers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spocrossgeomovedusers?view=sharepoint-ps&branch=pr-en-us-210) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C5%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204051857095085-210%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-06T18%3A58%3A23Z&sr=b&sp=r&sig=gsjnptvgfvqqD41%2F37k1vzMLqhjF7Cz0iaM4EgWmhio%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 19:04 UTC, merged