Update Set-SPOTenant.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #212
Opened 2022-04-01 17:55 UTC by timwoo187

2022-04-01 17:56 UTC, opbld30 commented
Docs Build status updates of commit _[12b9556](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/commits/12b95566cf5b42132fd3e2b5cfbc988b7b29bec7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-212) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C1%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204011755154407-212%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-02T17%3A56%3A30Z&sr=b&sp=r&sig=LdQeJjk15fYEqmecU6DYvSHNL%2BV03tSFsTlk2u8uRAA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-02 12:03 UTC, yogkumgit commented
@JohanFreelancer9

2022-04-04 03:43 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Enables reduced session timeout for temporary URLs used by apps for document download scenarios. Reduction occurs when app’s redeeming IP address does not match the original requesting IP. Default va
```suggestion
Enables reduced session timeout for temporary URLs used by apps for document download scenarios. Reduction occurs when an app redeeming an IP address does not match the original requesting IP. The default value is 15 minutes if ReduceTempTokenLifetimeValue is not set.
```

2022-04-04 03:43 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +> Reducing this value may bring degradation in end user experience by requiring frequent authentication prompts to users.
```suggestion
**Note**: Reducing this value may bring degradation in end-user experience by requiring frequent authentication prompts to users. 
```

2022-04-04 03:47 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Enables reduced session timeout for temporary URLs used by apps for document download scenarios. Reduction occurs when app’s redeeming IP address does not match the original requesting IP. Default va
```suggestion

Enables reduced session timeout for temporary URLs used by apps for document download scenarios. Reduction occurs when an app redeeming an IP address does not match the original requesting IP. The default value is 15 minutes if ReduceTempTokenLifetimeValue is not set.
```

2022-04-04 03:48 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +> Reducing this value may bring degradation in end user experience by requiring frequent authentication prompts to users.
```suggestion
**Note**: Reducing this value may bring degradation in end-user experience by requiring frequent authentication prompts to users. 
```

2022-04-04 03:49 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Optional parameter to set the session timeout value for temporary URLs. The value can be between 5-15 minutes and the default value is 15 minutes.
```suggestion

Optional parameter to set the session timeout value for temporary URLs. The value can be set between 5 and 15 minutes and the default value is 15 minutes.
```

2022-04-04 03:50 UTC, JohanFreelancer9 requested changes
Copy review - @timwoo187, kindly commit the suggested changes. Many thanks.

2022-04-04 12:47 UTC, opbld32 commented
Docs Build status updates of commit _[5ded2a5](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/commits/5ded2a5fe7567294492f1b10bbdd2696e0448cbf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-212) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204041245505759-212%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T12%3A47%3A04Z&sr=b&sp=r&sig=VSVicmCEfqr1qCqyvdNQ0bEaF6LW1ixlSapgdo0WeBA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-04 12:50 UTC, opbld33 commented
Docs Build status updates of commit _[0099fe8](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/commits/0099fe83339eba84c869c1719ecffd96150cf9e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-212) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204041246424238-212%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T12%3A49%3A59Z&sr=b&sp=r&sig=iTWdUOmNjsfgPquejGJWZWEkvc0MCabHpPbx7zJ5iOI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-05 04:33 UTC, JohanFreelancer9 approved these changes

2022-04-05 05:39 UTC, tseward commented
@timwoo187 could we have some verbiage added here or a link to another article that describes "temporary URLs"?

2022-04-06 00:31 UTC, get-itips reviewed
agree with @tseward

2022-04-07 01:47 UTC, yogkumgit commented
@timwoo187 Please update. Thanks

2022-04-13 03:38 UTC, yogkumgit commented
@timwoo187 Gentle reminder.

2022-04-13 04:16 UTC, timwoo187 commented
Temporary URLs are used with certain client scenarios similar to WAC token lifetime.

2022-04-14 14:47 UTC, yogkumgit commented
@dariomws @tseward

2022-04-14 18:23 UTC, tseward approved these changes

2022-04-15 12:21 UTC, yogkumgit commented
@dariomws

2022-04-17 14:28 UTC, yogkumgit commented
@dariomws Gentle reminder.

2022-04-19 07:04 UTC, dariomws approved these changes

2022-04-19 11:08 UTC, get-itips approved these changes

2022-04-19 11:45 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-19 14:15 UTC, opbld31 commented
Docs Build status updates of commit _[493ff4a](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/commits/493ff4a5b1ec9c9e9fe6af06ed93bc8da4a6e79b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0b14f3a5)

<a id="0b14f3a5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204191414362374-212%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T14%3A15%3A00Z&sr=b&sp=r&sig=lbQaaXE0bOp86Y36zarV3H9PaMqoWsuzBqnZ98H9%2F%2B4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 14:15 UTC, opbld32 commented
Docs Build status updates of commit _[ab723a9](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/commits/ab723a930e7dec3bcaa026f18536efcbfc3971dc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-70ff2974)

<a id="70ff2974"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204191414453387-212%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T14%3A15%3A30Z&sr=b&sp=r&sig=hjOoKX6lYhJZL%2BFuQ7ujQjkOTxxtdLLbVWfH8uuNH0g%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 14:17 UTC, opbld30 commented
Docs Build status updates of commit _[31786d3](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/commits/31786d33675f0a6685d8c23b40710cb57a4146ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/timwoo187/OfficeDocs-SharePoint-PowerShell/blob/patch-1/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-212) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204191415511520-212%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T14%3A17%3A01Z&sr=b&sp=r&sig=tVvPxBTsQByu4WTmUKkLYd8i98ZdFmIUfttVh1AsFH0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 14:17 UTC, merged