Update Get-SPOUserOneDriveLocation.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #225
Opened 2022-04-16 12:30 UTC by PowershellScripts

Suggested text for missing parameter description.

2022-04-16 12:32 UTC, opbld33 commented
Docs Build status updates of commit _[7c4883b](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/7c4883bf28bad2095fce1704cd45905df0c0e392)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-23/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouseronedrivelocation?view=sharepoint-ps&branch=pr-en-us-225) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C16%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204161230499200-225%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-17T12%3A32%3A06Z&sr=b&sp=r&sig=cx8KyElUtuHfkQp7uegTB2QkGjaYcTnUsQH32jlCUSE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-17 03:49 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md
> +UserPrincipalName or UPN defined for the specific user on the SPO tenant
```suggestion
UserPrincipalName or UPN defined for the specific user on the SPO tenant.
```

2022-04-17 03:51 UTC, JohanFreelancer9 requested changes
Copy review - @PowershellScripts, kindly commit the suggested change. Many thanks.

2022-04-18 16:10 UTC, yogkumgit commented
@PowershellScripts Gentle reminder, please implement the suggested changes. thanks

2022-04-19 13:47 UTC, opbld33 commented
Docs Build status updates of commit _[54509f5](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/54509f542510139b96d197e1e503df00c29ac3a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-23/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouseronedrivelocation?view=sharepoint-ps&branch=pr-en-us-225) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204191346246322-225%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T13%3A47%3A32Z&sr=b&sp=r&sig=5SDCP1rzT1%2FhzTLW9YNTuLQTioj57G%2ByfBa3VBxN7gs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 04:15 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-04-20 06:52 UTC, dariomws approved these changes

2022-04-20 11:32 UTC, get-itips approved these changes

2022-04-20 18:22 UTC, tseward approved these changes

2022-04-21 03:42 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-04-21 14:36 UTC, opbld32 commented
Docs Build status updates of commit _[8165edc](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/8165edcd999aab963866caa0fa5eb18d03a6b010)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-23/sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserOneDriveLocation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/get-spouseronedrivelocation?view=sharepoint-ps&branch=pr-en-us-225) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C21%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202204211435177212-225%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-22T14%3A36%3A42Z&sr=b&sp=r&sig=WdMaUDlIdz6xnp3cf0GjCq7KniHZCIqWUrFcda3VB9k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-21 14:37 UTC, merged