Adding -ShowPeoplePickerGroupSuggestionsForIB setting to Set-SPOTenant.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #239
Opened 2022-05-03 17:06 UTC by ZohrehHamrangsekachaie

Adding ShowPeoplePickerGroupSuggestionsForIB setting. Please @samkabue review this change.

2022-05-03 17:08 UTC, opbld33 commented
Docs Build status updates of commit _[b9703e6](https://github.com/ZohrehHamrangsekachaie/OfficeDocs-SharePoint-PowerShell/commits/b9703e69c31428a4fa40bde18f74bcd51d45b541)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/ZohrehHamrangsekachaie/OfficeDocs-SharePoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-239) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C3%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202205031706488249-239%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-03T17%3A08%3A01Z&sr=b&sp=r&sig=U4raJLHw7Fgf2g%2BhAONmiG3VowhYLZ3wCLQqKasyNEI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 07:55 UTC, yogkumgit commented
@JohanFreelancer9

2022-05-04 07:55 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2022-05-04 08:08 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +The ShowPeoplePickerGroupSuggestionsForIB setting (defaulted to false) will allow to show group suggestions for IB in the people picker.
```suggestion
The ShowPeoplePickerGroupSuggestionsForIB setting (defaulted to false) allows showing group suggestions for information barriers (IBs) in the People Picker.
```

2022-05-04 08:09 UTC, JohanFreelancer9 requested changes
Copy review - @ZohrehHamrangsekachaie, kindly commit the suggested changes if you agree with them. Many thanks.

2022-05-04 10:00 UTC, dariomws approved these changes
I'm ok after @JohanFreelancer9 suggestions. Thanks!

2022-05-04 12:28 UTC, get-itips commented
Hello @ZohrehHamrangsekachaie 
Tested in Microsoft.Online.SharePoint.PowerShell version 16.0.22413.12000 and it's still not there, is this going to be released in next version soon?
Thank you

2022-05-04 16:39 UTC, opbld31 commented
Docs Build status updates of commit _[d7f7c48](https://github.com/ZohrehHamrangsekachaie/OfficeDocs-SharePoint-PowerShell/commits/d7f7c4837d859f8e1bc34c5764cecc2a299e8da3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/ZohrehHamrangsekachaie/OfficeDocs-SharePoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-239) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C4%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202205041638245028-239%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-04T16%3A39%3A42Z&sr=b&sp=r&sig=4mPqHfYHXhrB7zM%2F4xkB2rSSRDtuQpF3jbb0fJxpBiQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-04 16:45 UTC, ZohrehHamrangsekachaie commented
> 

it has been released to SPDF as part of build16.0.22502.12000 at 4/29/2022 10:20 PM

2022-05-04 19:11 UTC, samkabue reviewed
@ZohrehHamrangsekachaie Please follow up with spacstrings to close on the string.

2022-05-04 21:48 UTC, tseward approved these changes

2022-05-06 03:40 UTC, yogkumgit commented
@ZohrehHamrangsekachaie

2022-05-06 03:57 UTC, samkabue approved these changes

2022-05-06 13:30 UTC, JohanFreelancer9 approved these changes

2022-05-07 10:08 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-05-09 12:33 UTC, opbld30 commented
Docs Build status updates of commit _[4ba03c4](https://github.com/ZohrehHamrangsekachaie/OfficeDocs-SharePoint-PowerShell/commits/4ba03c46af8d4921f40c02b0fe9471f30dc04aec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/ZohrehHamrangsekachaie/OfficeDocs-SharePoint-PowerShell/blob/main/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-239) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C9%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202205091232363026-239%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-09T12%3A33%3A56Z&sr=b&sp=r&sig=XRi7TcmSh4fK3rYgLm40RwDxm1uHVXJO1yBFOFMArOk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-09 12:35 UTC, merged