Change the help doc for SharePoint Powershell cmd
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #252
Opened 2022-06-07 07:56 UTC by mingzhangMicrosoft

2022-06-07 07:57 UTC, opbld30 commented
Docs Build status updates of commit _[01c28ee](https://github.com/mingzhangMicrosoft/OfficeDocs-SharePoint-PowerShell/commits/01c28eec734fa6cfa6a25349c73d0d1465db17b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-server-ps/sharepoint-server/Export-SPCertificate.md](https://github.com/mingzhangMicrosoft/OfficeDocs-SharePoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Export-SPCertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-server/export-spcertificate?view=sharepoint-server-ps&branch=pr-en-us-252) (sharepoint-server-ps) |
[sharepoint/sharepoint-server-ps/sharepoint-server/Renew-SPCertificate.md](https://github.com/mingzhangMicrosoft/OfficeDocs-SharePoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Renew-SPCertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-server/renew-spcertificate?view=sharepoint-server-ps&branch=pr-en-us-252) (sharepoint-server-ps) |
[sharepoint/sharepoint-server-ps/sharepoint-server/Switch-SPCertificate.md](https://github.com/mingzhangMicrosoft/OfficeDocs-SharePoint-PowerShell/blob/main/sharepoint/sharepoint-server-ps/sharepoint-server/Switch-SPCertificate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-server/switch-spcertificate?view=sharepoint-server-ps&branch=pr-en-us-252) (sharepoint-server-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202206070756212806-252/BuildReport?accessString=d22de4cdc4e4bdfdcafbf4cc308e265d53a339d982480dde48f1d91388c21332).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-09 09:10 UTC, yogkumgit commented
@JohanFreelancer9

2022-06-09 11:16 UTC, get-itips commented on sharepoint/sharepoint-server-ps/sharepoint-server/Export-SPCertificate.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
Why is this being changed from https to http?

2022-06-09 11:16 UTC, get-itips commented on sharepoint/sharepoint-server-ps/sharepoint-server/Switch-SPCertificate.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
Why is this being changed from https to http?

2022-06-09 11:18 UTC, get-itips commented on sharepoint/sharepoint-server-ps/sharepoint-server/Switch-SPCertificate.md
> +{{ Fill AssignmentCollection Description }}
What is the reason to remove the description? In case it's not valid, a valid one should be use instead an not a fill placeholder

2022-06-09 11:19 UTC, get-itips reviewed
Please review my comments, thank you

2022-06-10 05:39 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-server-ps/sharepoint-server/Renew-SPCertificate.md
> +online version:
Please insert the online version.

2022-06-10 05:44 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-server-ps/sharepoint-server/Renew-SPCertificate.md
> +If a key algorithm and key size / elliptic curve can't be found in the certificate to be renewed, the default key algorithm and key size / elliptic curve of the farm will be used.
```suggestion
If neither this parameter nor the KeySize parameter is specified, the key algorithm and key size/elliptic curve of the certificate to be renewed will be used.
If a key algorithm and key size/elliptic curve can't be found in the certificate to be renewed, the default key algorithm and key size/elliptic curve of the farm will be used.
```

2022-06-10 05:46 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-server-ps/sharepoint-server/Renew-SPCertificate.md
> +If a key algorithm and key size / elliptic curve can't be found in the certificate to be renewed, the default key algorithm and key size / elliptic curve of the farm will be used.
```suggestion
If neither this parameter nor the EllipticCurve parameter is specified, the key algorithm and key size/elliptic curve of the certificate to be renewed will be used.
If a key algorithm and key size/elliptic curve can't be found in the certificate to be renewed, the default key algorithm and key size/elliptic curve of the farm will be used.
```

2022-06-10 05:58 UTC, JohanFreelancer9 requested changes
Copy review - @mingzhangMicrosoft, kindly commit the suggested changes. Also, see @get-itips' comments.

2022-06-11 21:25 UTC, dariomws approved these changes
I'm ok after suggestions.

2022-06-13 06:10 UTC, yogkumgit commented
@mingzhangMicrosoft Gentle reminder

2022-06-16 04:56 UTC, yogkumgit commented
@mingzhangMicrosoft Gentle reminder

2022-06-20 10:14 UTC, yogkumgit commented
@tiburd Kindly reach out to PR owner. Thanks

2022-06-20 14:46 UTC, tiburd commented
sent email to @mingzhangMicrosoft

2022-07-28 02:13 UTC, yogkumgit commented
@mingzhangMicrosoft Please take a call on this PR. Please either implement the suggested changes and facilitate to merge this PR or please advise if changes are not required.
We will proceed to close it in the event of no response.
cc: @tiburd

2022-08-02 10:47 UTC, yogkumgit commented
Closing the PR as no response from the PR owner. Thanks

2022-08-02 10:47 UTC, closed without merging