Update Set-SPOTenantTaxonomyReplicationParameters.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #260
Opened 2022-06-13 15:25 UTC by PowershellScripts

Suggested text for missing parameter descriptions

2022-06-13 15:26 UTC, opbld30 commented
Docs Build status updates of commit _[e6e03be](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/e6e03be43da981179d364b7fe8a1d5cb00931189)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-26/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenanttaxonomyreplicationparameters?view=sharepoint-ps&branch=pr-en-us-260) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202206131525033716-260/BuildReport?accessString=c373a0e679f56a6e90d0d1670ed540a9fd23bb6d89c68b92ff0865ba50f8fae5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-14 06:56 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md
> +The parameter specifies whether all groups should be replicated.
```suggestion
This parameter specifies whether all groups should be replicated.
```

2022-06-14 06:56 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md
> +Specifies a comma separated list of groups that should be replicated.
```suggestion
Specifies a comma-separated list of groups that should be replicated.
```

2022-06-14 06:57 UTC, JohanFreelancer9 requested changes
Copy review - @PowershellScripts, kindly commit the suggested changes. Many thanks.

2022-06-14 07:26 UTC, yogkumgit commented
@get-itips @dariomws @tseward

2022-06-14 12:29 UTC, opbld33 commented
Docs Build status updates of commit _[2acdb9a](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/2acdb9a56134b194d216a689256698d90c4f6bb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-26/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenanttaxonomyreplicationparameters?view=sharepoint-ps&branch=pr-en-us-260) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202206141226276940-260/BuildReport?accessString=2b0d0008b45c5243a66f844b33ec62f2a85e7778bc909edc1ffd46cfedc44369).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-14 12:46 UTC, get-itips approved these changes

2022-06-14 15:33 UTC, dariomws approved these changes

2022-06-14 22:02 UTC, tseward approved these changes

2022-06-15 10:34 UTC, yogkumgit commented
@JohanFreelancer9

2022-06-15 12:14 UTC, JohanFreelancer9 approved these changes

2022-06-15 23:44 UTC, opbld32 commented
Docs Build status updates of commit _[264c58d](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/commits/264c58dc1da2f7f1fa0d43c058c978662d28f98a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md](https://github.com/PowershellScripts/OfficeDocs-SharePoint-PowerShell/blob/patch-26/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenanttaxonomyreplicationparameters?view=sharepoint-ps&branch=pr-en-us-260) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202206152342536831-260/BuildReport?accessString=9d0a0eb433ab5fbb4826d1f048ca8c6ab0360915cb66441bada1fc94440d429c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 04:57 UTC, yogkumgit commented
@tiburd

2022-06-16 14:29 UTC, merged