Add new cmdlets
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #289
Opened 2022-08-16 20:12 UTC by salarson

2022-08-16 20:13 UTC, opbld33 commented
Docs Build status updates of commit _[2ad715d](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/commits/2ad715d2d76529c0126f6a8e74e311b67cd3c9a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/blob/patch-7/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-289) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202208162012231502-289/BuildReport?accessString=4534769badbaf4f0470b1a64db8fb4bb91a6f7996cb4a5b72d49b7c079f46a59).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 03:57 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-17 03:58 UTC, yogkumgit commented
@get-itips @dariomws @tseward

2022-08-17 06:11 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Determines what level of sharing is available for the SharePoint Sites (Does not include OneDrive sites)
```suggestion
Determines what level of sharing is available for SharePoint sites (not including OneDrive sites).
```

2022-08-17 06:11 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Enable or Disable request files link on OneDrive partition for all OneDrive sites. If this value is not set, Request Files will only show for OneDrives with Anyone Links enabled.
```suggestion
Enable or disable the Request files link on the OneDrive partition for all OneDrive sites. If this value is not set, the Request files link will only show for OneDrives with Anyone links enabled. 
```

2022-08-17 06:12 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Enable or Disable request files link on OneDrive partition for all SharePoint sites (Not OneDrive Sites). If this value is not set, Request Files will only show for OneDrives with Anyone Links enable
```suggestion
Enable or disable the Request files link on the OneDrive partition for all SharePoint sites (not including OneDrive sites). If this value is not set, Request files will only show for OneDrives with Anyone links enabled. 
```

2022-08-17 06:14 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Specifies the number of days before an Request files link expires for all OneDrive Sites.
```suggestion
Specifies the number of days before a Request files link expires for all OneDrive sites. 
```

2022-08-17 06:14 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Value can be from 0 to 730 days.
```suggestion
The value can be from 0 to 730 days.
```

2022-08-17 06:15 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Specifies the number of days before an Request files link expires for all SharePoint sites (Not OneDrive sites)
```suggestion
Specifies the number of days before a Request files link expires for all SharePoint sites (not including OneDrive sites).
```

2022-08-17 06:15 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Value can be from 0 to 730 days.
```suggestion
The value can be from 0 to 730 days.
```

2022-08-17 06:16 UTC, JohanFreelancer9 requested changes
Copy review - @salarson, kindly commit the suggested changes if you agree with them. Many thanks.

2022-08-17 11:33 UTC, dariomws approved these changes

2022-08-17 12:51 UTC, opbld32 commented
Docs Build status updates of commit _[ad0193a](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/commits/ad0193a58f6d74e5b9595e7f53c164e2e525064e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/blob/patch-7/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-289) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202208171249582325-289/BuildReport?accessString=36e09510e1f14bb14fc464d0218c628ee18e87123cc1ae90900485205d6b7ee2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 12:53 UTC, opbld30 commented
Docs Build status updates of commit _[22d0f76](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/commits/22d0f7683f9860e5897dddcacacdafab15c80416)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/blob/patch-7/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-289) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202208171250197033-289/BuildReport?accessString=979bce348ed7ed1d3d10bc9b4fe6588b61b56449f1646bdc1a8b3f2b870c6c32).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-17 13:35 UTC, get-itips approved these changes

2022-08-17 16:07 UTC, JohanFreelancer9 approved these changes

2022-08-18 03:26 UTC, yogkumgit commented
@tseward

2022-08-18 23:05 UTC, tseward approved these changes

2022-08-19 05:29 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-19 18:21 UTC, opbld30 commented
Docs Build status updates of commit _[9d70f8f](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/commits/9d70f8f2132868df294599210531a6d23a00ac42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/blob/patch-7/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spotenant?view=sharepoint-ps&branch=pr-en-us-289) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202208191819579935-289/BuildReport?accessString=88cd97dbb5406f24633acdb4d45fd0121446077568d390431c9e57db85569977).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-19 18:21 UTC, merged