New Request Files cmds
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #293
Opened 2022-08-19 13:41 UTC by salarson

2022-08-19 13:43 UTC, opbld33 commented
Docs Build status updates of commit _[d7247cc](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/commits/d7247ccf323cb28e25684f77d63f2b1f7398a9bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/blob/patch-8/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-293) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202208191341532681-293/BuildReport?accessString=ecab064fb4054eb9ca2ed2d60dba5a13cf300a89f4c08f390f036e0639b6a1bc).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 04:20 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
> +Enables or disables Request Files link on the site.
```suggestion
Enables or disables the Request Files link on the site.
```

2022-08-22 04:21 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
> +Specifies the number of days before an Request files link expires for for the site.
```suggestion
Specifies the number of days before a Request Files link expires for the site.
```

2022-08-22 04:21 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
> +Value can be from 0 to 730 days.
```suggestion
The value can be from 0 to 730 days.
```

2022-08-22 04:22 UTC, JohanFreelancer9 requested changes
Copy review - @salarson, kindly commit the suggested changes. Many thanks.

2022-08-22 12:19 UTC, opbld32 commented
Docs Build status updates of commit _[b08ef77](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/commits/b08ef7712b443ca25b995ce5cac2627542b18b60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/blob/patch-8/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-293) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202208221217466983-293/BuildReport?accessString=df79ad74ea81787205382f861c11c87a01d7484d15def629e45c54591640f2db).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 12:20 UTC, opbld30 commented
Docs Build status updates of commit _[8699c24](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/commits/8699c24ce404683e871c1802bddd5dcabaaced89)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md](https://github.com/salarson/OfficeDocs-SharePoint-PowerShell/blob/patch-8/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-sposite?view=sharepoint-ps&branch=pr-en-us-293) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202208221218162048-293/BuildReport?accessString=29914738dec8611fb6074613fa60a81ac6560ed59c77d25a501495ee7e945a01).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-22 13:45 UTC, yogkumgit commented
@JohanFreelancer9

2022-08-22 13:46 UTC, yogkumgit commented
@dariomws @get-itips @tseward

2022-08-22 13:58 UTC, get-itips approved these changes

2022-08-22 14:29 UTC, tseward approved these changes

2022-08-22 14:35 UTC, JohanFreelancer9 approved these changes

2022-08-22 15:27 UTC, dariomws approved these changes

2022-08-23 10:54 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-08-23 13:37 UTC, merged