add example
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #314
Opened 2022-09-13 22:47 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/312

2022-09-13 22:49 UTC, opbld31 commented
Docs Build status updates of commit _[929ae33](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/929ae3303dc07434ecdf136e6eb5e7cc8044a493)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-24/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spotenantcdnorigin?view=sharepoint-ps&branch=pr-en-us-314) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202209132248019000-314/BuildReport?accessString=c6a720c21bdc2daf5924f610480f5a8880c4b6df0512e7c939285434729dd70c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-14 05:02 UTC, yogkumgit commented
@dariomws @tseward

2022-09-14 06:51 UTC, dariomws approved these changes

2022-09-14 07:53 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md
> +This example removes a recently-removed organizational assets library from CDN.
```suggestion
This example removes a recently-removed organizational assets library from a CDN.
```

2022-09-14 07:53 UTC, JohanFreelancer9 requested changes
Copy review.

2022-09-14 23:27 UTC, tseward approved these changes

2022-09-15 07:00 UTC, yogkumgit commented
@get-itips

2022-09-15 12:45 UTC, opbld32 commented
Docs Build status updates of commit _[1ebb19a](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/1ebb19a5425106d1ce7f29c788694ef2502f9826)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-24/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spotenantcdnorigin?view=sharepoint-ps&branch=pr-en-us-314) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202209151244080910-314/BuildReport?accessString=feee3635d8d51a57278f743055b79832e9559109fe14bffd15947403ec032435).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 17:47 UTC, JohanFreelancer9 approved these changes

2022-09-16 04:39 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2022-09-16 15:49 UTC, opbld31 commented
Docs Build status updates of commit _[1ff7825](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/1ff78252319c64a246ca40790df7b335c5d3d473)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-24/sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantCdnOrigin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spotenantcdnorigin?view=sharepoint-ps&branch=pr-en-us-314) (sharepoint-ps) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202209161548142347-314/BuildReport?accessString=1932a536080e65402a966fe955ce10acc934066bdcdf37f80b91718b8be6e83c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 15:50 UTC, merged