clarify
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #336
Opened 2022-10-07 17:38 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/317

@tseward @dariomws what do you think?

2022-10-07 17:40 UTC, opbld31 commented
Learn Build status updates of commit _[8823b70](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/8823b7012ce62e0d629bf55db7731e4a767ee28a)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-26/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md) | :bulb:Suggestion | [View](https://review.learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?branch=pr-en-us-336) | [Details](#user-content-d4f427fa6ec1121674a4136451d79175-7790191a)

<a id="d4f427fa6ec1121674a4136451d79175-7790191a"></a>
### [sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-26/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md)
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202210071738236120-336/BuildReport?accessString=6f6d3fd63252007a56d03bf8e6272198d0a50f7c0af75cd0bfcd6cc7007f8578).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 17:45 UTC, opbld30 commented
Learn Build status updates of commit _[331d742](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/331d7420d7855a6ac8a463d9748fcf87ab2f94fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-26/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?branch=pr-en-us-336) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202210071744215213-336/BuildReport?accessString=71f41c0c3699fca596ca0816d513f3706261871d0f917c2301d1eddd499af1b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 18:51 UTC, tseward reviewed
You indicate 'installed on the same computer' and then go to reference SharePoint Server. Is it the same computer (yes) or exclusive to SharePoint Server (no).

2022-10-07 18:53 UTC, get-itips commented
Well, the same computer text was already there, what I want to express is the following:

regular computer with client components sdk -> safe to uninstall

SharePoint server  -> do not uninstall as you will break SP

What do you think?

2022-10-07 20:33 UTC, dariomws reviewed
If SharePoint Client Components SDK is included in every installation of SharePoint Server because it's a required component, I think we can add a new note saying that SPO Management Shell is not supported in SP servers.
Anyway, I think this is a very special situation to install the SPO MS in an SP server...

2022-10-08 07:46 UTC, JohanFreelancer9 commented on sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
> +> There is a known issue between the SharePoint Online Management Shell module and SharePoint Client Components SDK where the module will fail to load if both are installed on the same computer. If y
```suggestion
> There is a known issue between the SharePoint Online Management Shell module and SharePoint Client Components SDK where the module will fail to load if both are installed on the same computer. If you encounter this issue and you are not trying to use the SharePoint Online Management Shell module in a SharePoint Server, uninstall the SharePoint Client Components SDK.
```

2022-10-08 07:46 UTC, JohanFreelancer9 requested changes
Copy review.

2022-10-10 13:53 UTC, yogkumgit commented
@get-itips copy review. @tseward please comment

2022-10-10 15:53 UTC, tseward requested changes

2022-10-10 15:53 UTC, tseward commented on sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
> +> There is a known issue between the SharePoint Online Management Shell module and SharePoint Client Components SDK where the module will fail to load if both are installed on the same computer. If y
> There is a known issue between the SharePoint Online Management Shell module and SharePoint Client Components SDK where the module will fail to load if both are installed on the same computer (excluding a computer running SharePoint Server). If you encounter this issue uninstall the SharePoint Client Components SDK.

2022-10-10 18:45 UTC, opbld32 commented
Learn Build status updates of commit _[08b17ef](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/08b17ef4a7d5f35cd269411df0435690441b4553)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-26/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?branch=pr-en-us-336) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202210101843471641-336/BuildReport?accessString=9c83b28ac85eb71a5788c519a01db23487184789f37960b55532626be3d0d92b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 06:18 UTC, JohanFreelancer9 approved these changes

2022-10-11 13:35 UTC, dariomws reviewed
I'm not sure if we can add this information, to be honest. I cannot approve.

2022-10-11 15:15 UTC, yogkumgit commented
@get-itips and @tseward Please discuss it with Dario and resolve.

2022-10-11 15:33 UTC, get-itips commented
Closing as no consensus for approval was achieved.

2022-10-11 15:36 UTC, opbld31 commented
Learn Build status updates of commit _[08b17ef](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/commits/08b17ef4a7d5f35cd269411df0435690441b4553)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-26/sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?branch=pr-en-us-336) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d/202210111534424450-336/BuildReport?accessString=700ed554ce4662bfb0c566ea61f465ea4f9d83bd74e7c37a5e194bc462bc14bd).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-11 15:36 UTC, closed without merging