Update ResyncTenantPrivacy and Expiration cmds
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #392
Opened 2023-02-17 15:28 UTC by salarson

2023-02-18 05:58 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Running 'Set-SPOTenant - ReSyncTenantPrivacyProfile' will force to a sync from Azure Active Directory privacy profile url to SharePoint Online immediately. There is a 1 day synchronization time windo
```suggestion
Running 'Set-SPOTenant - ReSyncTenantPrivacyProfile' will force a sync from the Azure Active Directory privacy profile URL to SharePoint Online immediately. There is a one-day synchronization time window. Whenever SharePoint Online gets the privacy profile URL, it checks whether the last sync time is out of the sync time window. If it is, it syncs from Azure Active Directory to SharePoint Online.
```

2023-02-18 05:59 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-19 09:36 UTC, JohanFreelancer9 approved these changes

2023-02-20 12:30 UTC, dariomws approved these changes

2023-02-20 12:36 UTC, get-itips approved these changes

2023-02-21 13:27 UTC, yogkumgit commented
@tseward

2023-02-22 13:09 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-02-22 17:30 UTC, tiburd commented
@salarson 
Hi Sam - can you please respond to Trevor's question above:
![image](https://user-images.githubusercontent.com/54688693/220708454-699b40d2-44f2-4846-8ed9-a69bbf941445.png)

Thank you!

2023-02-22 17:40 UTC, merged