Clarify permission
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #421
Opened 2023-03-28 17:14 UTC by get-itips

closes https://github.com/MicrosoftDocs/office-docs-powershell/issues/10645

2023-03-29 15:06 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md
> +Connects a top-level SPO site collection to a new Microsoft 365 Group.  You must be a SharePoint Online administrator or Global Administrator to run the cmdlet, and be a site collection administrator
```suggestion
Connects a top-level SPO site collection to a new Microsoft 365 Group. You must be a SharePoint Online administrator or Global administrator to run the cmdlet and be a site collection administrator of the site.
```

2023-03-29 15:07 UTC, JohanFreelancer9 approved these changes

2023-03-29 18:34 UTC, JohanFreelancer9 requested changes
Approved with minor suggestions.

2023-03-29 21:22 UTC, JohanFreelancer9 approved these changes

2023-03-29 21:30 UTC, dariomws approved these changes

2023-03-30 15:28 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-03-30 15:44 UTC, merged