Add doc to support SiteOwnerManageLegacyServicePrincipalEnabled on Se…
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #432
Opened 2023-04-11 09:54 UTC by RongqiZ

…t-SPOTenant.md

2023-04-11 13:26 UTC, dariomws reviewed
@RongqiZ, will this parameter be included in the next release?

2023-04-11 18:20 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +When the value is set to false, only tenant admins can create or update the Azure Access Control (ACS) service principal from the admin center. If the value is set to True, both tenant admins and sit
```suggestion
Allows or disallows the site owner to manage the Azure Access Control (ACS) service principal.

When the value is set to false, only tenant admins can create or update the ACS service principal from the admin center. If the value is set to True, both tenant admins and site owners can create or update the ACS service principal.
```

2023-04-11 18:21 UTC, JohanFreelancer9 requested changes
Copy review - @RongqiZ, kindly commit the suggested changes. Many thanks.

2023-04-11 18:21 UTC, get-itips approved these changes

2023-04-12 02:42 UTC, RongqiZ commented
> @RongqiZ, will this parameter be included in the next release?

This will release in weeks, I will merge this PR after the ps command parameter in 100% prod.

2023-04-12 07:57 UTC, dariomws approved these changes

2023-04-12 16:40 UTC, JohanFreelancer9 approved these changes

2023-04-12 16:56 UTC, yogkumgit commented
@tseward

2023-05-08 12:31 UTC, dariomws commented
@RongqiZ, please let us know when it can be merged. Thanks!

2023-05-09 02:07 UTC, RongqiZ commented
> @RongqiZ, please let us know when it can be merged. Thanks!

Hi @dariomws, the code merged on April 25, I checked the release process, it will be forked in mid May and release on end of May. We could merge this by end of this month.

2023-06-08 11:22 UTC, yogkumgit commented
@RongqiZ Kindly suggest, can this be merged?

2023-07-04 14:39 UTC, yogkumgit commented
@tiburd please investigate the status internally and take an action. Thanks

2023-07-05 02:58 UTC, RongqiZ commented
> @RongqiZ Kindly suggest, can this be merged?

Hi we are waiting for the review results, and we planned to release this feature in Aug. We could merge this before that.

2023-08-30 03:07 UTC, RongqiZ commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +When the value is set to false, only SharePoint tenant admins can create or update the ACS service principal from the admin center. If the value is set to true, both SharePoint tenant admins and site
Updated

2023-08-30 09:18 UTC, RongqiZ commented
Hi @yogkumgit @tiburd 
We are going to release the feature in the PR. Could you help to complete the PR for us? Many thanks!

2023-08-30 14:16 UTC, tiburd commented
@RongqiZ
Hi,
If this PR is ready to merge, please remove "[Do Not Merge]" from the title and @ mention me again.
Thank you!

2023-08-31 02:21 UTC, RongqiZ commented
Hi @tiburd 
Thanks for reminding! I removed the [Do Not Merge] in the title.

2023-08-31 10:09 UTC, merged

2023-08-31 10:09 UTC, VesaJuvonen commented
Merging this to align with the conceptual docs which were just merged/updated and published.

Parameter has been in the SPO PowerShell cmdlets since the 16.0.23702.12000 release - so three months and flights are now rolling to production - so good to get this published as well.