Update Set-SPOTenant.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #444
Opened 2023-04-28 00:02 UTC by nishantbhatt09

Add MediaAutomaticTranscriptionFeature tenant setting

2023-04-28 05:56 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Possible values:
```suggestion
When the feature is enabled, videos can have transcripts generated automatically on upload. The policy is default on. If a tenant admin decides to disable the feature, he can do so by disabling the policy at tenant level. This feature can not be enabled or disabled at site level.

Possible values are:
```

2023-04-28 05:57 UTC, JohanFreelancer9 requested changes
Copy review - @nishantbhatt09, kindly commit the suggested change. Many thanks.

2023-05-01 14:25 UTC, yogkumgit commented
@nishantbhatt09 Please implement the suggested changes. Thanks

2023-05-01 14:39 UTC, get-itips approved these changes

2023-05-02 07:55 UTC, dariomws approved these changes

2023-05-02 16:54 UTC, nishantbhatt09 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Possible values:
Addressed your comment

2023-05-03 05:05 UTC, JohanFreelancer9 approved these changes

2023-05-03 12:27 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-05-03 15:20 UTC, merged