Create Get-SPOListDesign.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #463
Opened 2023-06-16 16:41 UTC by SaladiHarini

Adding a new cmdlet to support the Custom List Templates feature!

2023-06-18 09:31 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListDesign.md
> +This example and sample response show how to get list design details.
```suggestion
```

2023-06-18 09:31 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListDesign.md
> +
```suggestion

This example and sample response show how to get list design details. 

```

2023-06-18 09:32 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListDesign.md
> +This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and
```suggestion
This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable, -InformationAction, -InformationVariable, -OutVariable, -OutBuffer, -PipelineVariable, -Verbose, -WarningAction, and -WarningVariable. For more information, see [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
```

2023-06-18 09:32 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListDesign.md
> +### Microsoft.Online.SharePoint.PowerShell.SPOListDesignPipeBind
```suggestion
Microsoft.Online.SharePoint.PowerShell.SPOListDesignPipeBind
```

2023-06-18 09:32 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListDesign.md
> +### System.Object
```suggestion
System.Object

```

2023-06-18 09:32 UTC, JohanFreelancer9 requested changes
Copy review - @SaladiHarini, kindly commit the suggested changes. Many thanks.

2023-06-19 10:20 UTC, yogkumgit commented
@SaladiHarini Please implement the suggested changes. Thanks

2023-06-21 07:45 UTC, JohanFreelancer9 approved these changes

2023-06-22 11:17 UTC, yogkumgit commented
@SaladiHarini Please implement the suggested changes. Thanks

2023-06-27 15:35 UTC, SaladiHarini commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListDesign.md
> +Get-SPOListDesign 44252d09-62c4-4913-9eb0-a2a8b8d7f863
Added!

2023-06-27 16:48 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListDesign.md
> +online version:
```suggestion
online version: https://learn.microsoft.com/powershell/module/sharepoint-online/get-spolistdesign
```

2023-06-27 16:49 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListDesign.md
> +---
```suggestion
title: Get-SPOListDesign
---
```

2023-06-27 16:50 UTC, get-itips commented
> @get-itips I've made the requested changes by adding author metadata + adding the -Identity param to the example. Please review and let me know if any other changes needed here. At this point, this build is not failing, so phew!

Thank you, please see last requested changes

2023-06-27 20:16 UTC, get-itips approved these changes

2023-06-28 12:07 UTC, yogkumgit commented
@tseward Please review. Thanks

2023-06-30 12:03 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-06-30 17:45 UTC, tiburd commented
close > reopen

2023-06-30 17:50 UTC, merged