Add private preview use
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #488
Opened 2023-07-07 15:09 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/482

2023-07-08 03:59 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +> This parameter is currently under private preview use.
```suggestion
> This parameter is currently under private preview.
```

2023-07-08 03:59 UTC, JohanFreelancer9 requested changes
Copy review.

2023-07-10 11:47 UTC, yogkumgit commented
@get-itips

2023-07-10 11:48 UTC, yogkumgit commented
@JohanFreelancer9

2023-07-10 13:09 UTC, JohanFreelancer9 approved these changes

2023-07-11 02:50 UTC, yogkumgit commented
@get-itips

2023-07-12 04:01 UTC, yogkumgit commented
@tseward

2023-07-13 11:36 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-07-13 15:03 UTC, merged