Update Start-SPOTenantRename.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #497
Opened 2023-07-26 20:29 UTC by MSFT-GRRojas

Added not available for GCC, GCC High & DoD.

2023-07-27 08:05 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Start-SPOTenantRename.md
> +> This feature is currently available to organizations that have no more than 10,000 total SharePoint sites and OneDrive accounts combined.  Additionally, tenant rename capability is not available fo
```suggestion
> This feature is currently available to organizations that have no more than 10,000 total SharePoint sites and OneDrive accounts combined.  Additionally, tenant renaming capability is not available for GCC, GCC High, and DoD.
```

2023-07-27 08:06 UTC, JohanFreelancer9 requested changes
Copy review - @MSFT-GRRojas, kindly commit the suggested changes. Many thanks.

2023-07-27 13:15 UTC, get-itips approved these changes
I'm ok after Johan's suggestions are applied

2023-07-28 11:09 UTC, yogkumgit commented
@MSFT-GRRojas Gentle reminder. Thanks

2023-07-28 15:16 UTC, JohanFreelancer9 approved these changes

2023-08-07 08:36 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-08-07 18:29 UTC, merged