Update connect-sharepoint-online.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #498
Opened 2023-08-01 19:36 UTC by Michal-Ziemba

Added a note about incompatibility to PowerShell ver 7 and how to mitigate it.

2023-08-02 07:40 UTC, JohanFreelancer9 commented on sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
> +
```suggestion
>   ```

```

2023-08-02 07:41 UTC, JohanFreelancer9 requested changes
Copy review - @Michal-Ziemba, kindly commit the suggested change. Many thanks.

2023-08-02 16:46 UTC, get-itips commented
Maybe @salarson should review this one too @yogkumgit

2023-08-02 16:47 UTC, get-itips approved these changes

2023-08-03 13:33 UTC, yogkumgit commented
@salarson please review. Thanks

2023-08-03 13:46 UTC, salarson approved these changes

2023-08-03 14:34 UTC, JohanFreelancer9 approved these changes

2023-08-07 08:39 UTC, yogkumgit commented
@Michal-Ziemba Closing this PR, as this is not approved. Thanks for taking out some time and creating this PR. Appreciate and encourage you to do the same in future also.

2023-08-07 08:39 UTC, closed without merging