Add new para <SecureSocketsLayer>to Set-SPPeoplePickerConfig and Add-SPPeoplePickerSearchADDomain
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #508
Opened 2023-09-06 03:03 UTC by xinyiHugeHard

2023-09-06 07:46 UTC, yogkumgit commented
@JohanFreelancer9

2023-09-06 09:22 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-server-ps/sharepoint-server/Add-SPPeoplePickerSearchADDomain.md
> +Whether the new added forest or domain should enable Secure LDAP (LDAPS).
```suggestion
Specifies whether the newly added forest or domain should enable Secure LDAP (LDAPS).
```

2023-09-06 09:23 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-06 16:58 UTC, get-itips approved these changes
I'm ok after @JohanFreelancer9 suggestions and also both SecureSocketsLayer descriptions should match

2023-09-07 04:33 UTC, JohanFreelancer9 approved these changes

2023-09-14 13:01 UTC, tiburd commented
> I'm ok after @JohanFreelancer9 suggestions and also both SecureSocketsLayer descriptions should match

@xinyiHugeHard 
Please update to that the description for SecureSocketsLayer is the same in both files.
After you do that, please @ mention me.

Thank you

2023-09-18 08:04 UTC, xinyiHugeHard commented
@tiburd Sorry for the late response, currently description of SecureSocketsLayer  in 2 files are both started with "Specifies whether " I don't think SecureSocketsLayer should have the same description in 2 files.

2023-09-18 15:44 UTC, tiburd commented
> @tiburd Sorry for the late response, currently description of SecureSocketsLayer in 2 files are both started with "Specifies whether " I don't think SecureSocketsLayer should have the same description in 2 files.

@get-itips 
Hi Andres,
Can you please review my comment (in which I tried to repeat your comment) and Xinyi's response?
Thanks!

2023-09-18 16:44 UTC, get-itips commented
I reviewed again and it is ok as it is as cmdlets are different @tiburd

2023-09-18 16:53 UTC, merged