Clarify domain guid
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #513
Opened 2023-09-11 14:22 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/510

2023-09-11 16:14 UTC, yogkumgit commented
@JohanFreelancer9

2023-09-12 02:29 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantSyncClientRestriction.md
> +Sets the [domain GUID](/powershell/module/activedirectory/get-addomain) of the computer domain membership to add to the safe recipient list. Requires a minimum of 1 domain GUID. The maximum number of
```suggestion
Sets the [domain GUID](/powershell/module/activedirectory/get-addomain) of the computer domain membership to add to the safe recipient list. Requires a minimum of one domain GUID. The maximum number of domain GUIDs allowed is 125.
```

2023-09-12 02:29 UTC, JohanFreelancer9 requested changes
Copy review.

2023-09-15 06:37 UTC, msbemba approved these changes

2023-09-15 12:13 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2023-09-15 14:49 UTC, merged