Add Set-SPOContainer.md, add authors, and remove comments
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #566
Opened 2023-11-27 22:35 UTC by cindylay

@abiramisuresh Adding documentation for the new SPO PowerShell command `Set-SPOContainer`

2023-11-28 16:10 UTC, yogkumgit commented
@JohanFreelancer9

2023-11-28 16:30 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +For permissions and the most current information about Windows PowerShell for SharePoint Embedded Containers, see the online documentation at [Intro to SharePoint Embedded Containers Management Shell
```suggestion
For permissions and the most current information about Windows PowerShell for SharePoint Embedded Containers, see the online documentation at [Intro to SharePoint Embedded Containers Management Shell](/powershell/sharepoint/sharepoint-online/introduction-sharepoint-online-management-shell?view=sharepoint-ps).
```

2023-11-28 16:30 UTC, get-itips commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +Blocking the download of files allows users to remain productive while addressing the risk of accidental data loss. Users have browser-only access with no ability to download, print, or sync files. T
```suggestion
Blocking the download of files allows users to remain productive while addressing the risk of accidental data loss. Users have browser-only access with no ability to download, print, or sync files. They also won't be able to access content through apps, including the Microsoft Office desktop apps. When web access is limited, users will see the following message at the top of Containers: "Your organization doesn't allow you to download, print, or sync from this Container. For help contact your IT department." Read the full documentation for advanced capabilities at [Block download policy for SharePoint Containers and OneDrive](/sharepoint/block-download-from-Containers).
```

2023-11-29 07:36 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +Sets or updates one or more properties' values for a Container in SharePoint Embedded.
```suggestion
Sets or updates one or more property values for a Container in SharePoint Embedded.
```

2023-11-29 07:36 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:36 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:37 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:37 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:37 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:37 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:37 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +As a SharePoint administrator or global administrator in Microsoft 365, you can block the download of files from SharePoint Embedded Containers. This feature does not need Microsoft Entra Conditional
```suggestion
As a SharePoint Administrator or Global Administrator in Microsoft 365, you can block the download of files from SharePoint Embedded Containers. This feature does not need Microsoft Entra Conditional Access policies. This feature can be set for individual Containers but not at the organization level.
```

2023-11-29 07:37 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:37 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +Please read [Control access from unmanaged devices](/sharepoint/control-access-from-unmanaged-devices) documentation here to understand Conditional Access Policy usage in SharePoint Embedded Containe
```suggestion
Read the [Control access from unmanaged devices](/sharepoint/control-access-from-unmanaged-devices) documentation to understand Conditional Access Policy usage in SharePoint Embedded Container.
```

2023-11-29 07:38 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
- BlockAccess: Blocks access.
```

2023-11-29 07:38 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:38 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +Used to specify the unique identifier (GUID) of the SensitivityLabel.
```suggestion
Specifies the unique identifier (GUID) of the SensitivityLabel.
```

2023-11-29 07:38 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
> +
```suggestion
```

2023-11-29 07:42 UTC, JohanFreelancer9 requested changes
Copy review - @cindylay, kindly commit the suggested changes. Many thanks.

2023-11-29 14:53 UTC, abiramisuresh approved these changes

2023-12-05 13:20 UTC, msbemba approved these changes

2023-12-11 15:58 UTC, yogkumgit commented
@tiburd Please help us in resolving this issue. Thanks

2023-12-11 17:47 UTC, merged