Add IsDataAccessInCardDesignerEnabled flag
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #572
Opened 2023-12-13 20:11 UTC by nick-pape

See documentation here: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/viva/features/card-designer/card-designer-api-support

2023-12-15 07:29 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +Note: Further documentation on this feature is available [here](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/viva/features/card-designer/card-designer-api-support).
```suggestion
For further documentation on this feature, see [Overview of Viva Connections Card Designer advance API features](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/viva/features/card-designer/card-designer-api-support).
```

2023-12-15 07:30 UTC, JohanFreelancer9 requested changes
Copy review - @nick-pape, kindly commit the suggested change. Many thanks.

2024-03-16 03:47 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +The valid values are:
>   [](http://example.com/codeflow?start=21&length=2)

remove trailing spaces

2024-03-16 03:47 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +- False (default) – SharePoint and Graph API's cannot be accessed in the Card Designer card.
>API's [](http://example.com/codeflow?start=41&length=5)

should be "APIs" not "API's"

2024-03-16 03:48 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
> +- True – Users with edit permissions on the Dashboard will be able to access SharePoint and Graph API's in the Card Designer card.
>API's [](http://example.com/codeflow?start=98&length=5)

should be "APIs" not "API's"

2024-04-10 15:09 UTC, nick-pape commented
@samkabue @JohanFreelancer9 should be good to go now!

2024-04-10 16:42 UTC, samkabue approved these changes
:shipit:

2024-04-10 16:51 UTC, merged