Update Unlock-SPOSensitivityLabelEncryptedFile.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #573
Opened 2023-12-15 18:53 UTC by SanjoyanM

2023-12-16 05:55 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Unlock-SPOSensitivityLabelEncryptedFile.md
> +You must be a SharePoint Online administrator or Global Administrator to run the `Unlock-SPOSensitivityLabelEncryptedFile` cmdlet. Note, this cmdlet do not work on files that have double key encrypti
```suggestion
You must be a SharePoint Online administrator or Global Administrator to run the `Unlock-SPOSensitivityLabelEncryptedFile` cmdlet. Note, this cmdlet does not work on files that have double key encryption or files that have encryption but are not processed by SharePoint. Such files do not show the name of the label in the sensitivity column and such files can't be edited in Office Online.
```

2023-12-16 05:56 UTC, JohanFreelancer9 requested changes
Copy review - @SanjoyanM, kindly commit the suggested change. Many thanks.

2023-12-19 06:56 UTC, JohanFreelancer9 approved these changes

2023-12-19 15:32 UTC, SanjoyanM commented
[like]  Sanjoyan Mustafi reacted to your message:
________________________________
From: JohanFreelancer9 ***@***.***>
Sent: Tuesday, December 19, 2023 6:56:54 AM
To: MicrosoftDocs/OfficeDocs-SharePoint-PowerShell ***@***.***>
Cc: Sanjoyan Mustafi ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint-PowerShell] Update Unlock-SPOSensitivityLabelEncryptedFile.md (PR #573)


@JohanFreelancer9 approved this pull request.

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/573#pullrequestreview-1788215055>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALFJCUBC6FRX3RIDOURKZETYKE3DNAVCNFSM6AAAAABAW3L3QSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBYGIYTKMBVGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-01-09 00:08 UTC, merged