Add commands for managing built-in font packages
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #659
Opened 2024-08-06 10:32 UTC by Yixian15

Add commands for managing built-in font packages.

2024-08-06 17:04 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInFontPackageSettings.md
> +Gets settings of built-in font packages.
I feel this could be improved a little bit, e.g., to add a bit more info? I'd suggest you work with your PM on this PR.

2024-08-06 17:06 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInFontPackageSettings.md
> +## EXAMPLE
this should be
level 2 header: EXAMPLES
level 3 header: EXAMPLE

```
## EXAMPLES
### EXAMPLE
```

2024-08-06 17:06 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInFontPackageSettings.md
> +
remove as you don't have params

2024-08-06 17:07 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInFontPackageSettings.md
> +Gets settings of built-in font packages.
(applies to the other file too)

2024-08-06 17:08 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInFontPackageSettings.md
> +Hide built in font packages from SharePoint sites if this value is true.
>Hide built [](http://example.com/codeflow?start=0&length=10)

please work with your PM on this documentation. e.g., from reading this, it's not clear what "hiding" means/what effect it has etc

2024-08-06 17:08 UTC, samkabue requested changes
:clock1:

2025-01-25 00:28 UTC, samkabue commented
You also need to update the table of contents file `sharepoint-online.md`

2025-02-11 17:48 UTC, samkabue commented
> 

add `## RELATED LINKS` section, and cross-reference your 2 cmdlets

See example PR: [https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/808/files](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/808/files)

---
Refers to: sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInFontPackageSettings.md:38 in e9fffa2. [](commit_id = e9fffa2edc8982f0864a67a114dca1b6c2983ff0, deletion_comment = False)

2025-02-18 03:36 UTC, wfwf1997 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInFontPackageSettings.md
> +This example retrieves the current settings of built-in font packages.
>retrieves [](http://example.com/codeflow?start=13&length=9)

Retrive?

2025-02-25 07:03 UTC, samkabue approved these changes
:shipit:

2025-02-25 07:52 UTC, merged