New Container type lifecycle cmdlets
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #755
Opened 2024-11-13 08:17 UTC by ShreyasSar26

2025-01-23 00:47 UTC, AdwoodMicrosoft approved these changes

2025-01-25 00:12 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -Identity <ContainerId>
could you use PlatyPS to generate these syntax? e.g. when I use it to generate the documentation skeleton:

```
Install-Module -Name platyPS
Import-Module platyPS

New-MarkdownHelp -Command "Get-SPOContainer" -OutputFolder E:\  
```

this is what I get for this cmdlet:

```
### Identity

Get-SPOContainer -Identity <SPOContainerPipeBind> [<CommonParameters>]
```

2025-01-25 00:13 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -Identity <ContainerId>
applies to the other files and cmdlets

2025-01-25 00:13 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +The `Get-SPOContainer` cmdlet retrieves and returns the details of an individual container when paired `Identity` parameter, where the container ID needs to be mentioned. The cmdlet returns the list
>paired [](http://example.com/codeflow?start=96&length=6)

paired "with"?

2025-01-25 00:13 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +You must be a SharePoint Embedded Administrator to run the cmdlet.
>the [](http://example.com/codeflow?start=55&length=3)

this

2025-01-25 00:14 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45-jikl-9bnm-b302-1234ghy56789 | FT
>FT [](http://example.com/codeflow?start=77&length=2)

here and other places/files: 

we generally use lowercase `ft`

2025-01-25 00:15 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45-jikl-9bnm-b302-1234ghy56789 -SortByStorage <Ascending>-Paged
missing space before `-Paged`

same for the next example

2025-01-25 00:16 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45-jikl-9bnm-b302-1234ghy56789 -Paged -PagingToken <Token String> | FT
><Token String> [](http://example.com/codeflow?start=95&length=14)

give a short random string here, since this is just an example

2025-01-25 00:16 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45-jikl-9bnm-b302-1234ghy56789 -SortByStorage <Ascending>
><Ascending> [](http://example.com/codeflow?start=90&length=11)

do you mean `Ascending` (i.e. without the < >)

2025-01-25 00:17 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45-jikl-9bnm-b302-1234ghy56789 -SortByStorage <Ascending>
same with the other examples

2025-01-25 00:17 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45-jikl-9bnm-b302-1234ghy56789 -Paged -PagingToken <Token String> | FT
same with the other examples

2025-01-25 00:17 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Example 7 displays the next list of paged view  of containers belonging to the application, sorted in ascending order of storage
>  [](http://example.com/codeflow?start=46&length=1)

extra space

2025-01-25 00:17 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to specify the Container ID of a container.
>Container [](http://example.com/codeflow?start=34&length=9)

remove "Container" since it's a dupe

2025-01-25 00:18 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +This parameter can be used when there are more than 200 Containers in a given SharePoint Embedded application. Using `-Paged` will provide a `<Paging Token>` that will display the next 200 Containers
>`<Paging Token>` [](http://example.com/codeflow?start=141&length=16)

paging token

2025-01-25 00:18 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the `<Paging Token>` provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the m
>`<Paging Token>` [](http://example.com/codeflow?start=34&length=16)

paging token

2025-01-25 00:18 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the `<Paging Token>` provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the m
other places too

2025-01-25 00:19 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the `<Paging Token>` provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the m
>End of Containers view [](http://example.com/codeflow?start=207&length=22)

is this the exact string that's returned?

2025-01-25 00:20 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
> +This cmdlet creates a new standard or trial container type. A standard container type, by definition, has a billing profile associated with it and can be either regular billed or direct to consumer b
>  [](http://example.com/codeflow?start=602&length=1)

extra space

2025-01-25 00:20 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
> +This cmdlet creates a new standard or trial container type. A standard container type, by definition, has a billing profile associated with it and can be either regular billed or direct to consumer b
>, [](http://example.com/codeflow?start=665&length=1)

remove `,`

2025-01-25 00:21 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
> +New-SPOContainerType – IsPassThroughBilling – ContainerTypeName “ContosoLegal” -OwningApplicationId a735e4af-b86e-0000-93ba-1faded6c39e1
>“ [](http://example.com/codeflow?start=64&length=1)

use regular `"`

2025-01-25 00:21 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
> +New-SPOContainerType –TrialContainerType - ContosoLegal -OwningApplicationId a735e4af-b86e-0000-93ba-1faded6c39e1
>-  [](http://example.com/codeflow?start=41&length=2)

I think this `-` here should be removed?

2025-01-25 00:22 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerType.md
> +While you only need to be a SharePoint Embedded Administrator to change the basic information of a container type, you need owner/contributor access on the existing billing subscription associated wi
>owner/ [](http://example.com/codeflow?start=124&length=6)

owner or

2025-01-25 00:23 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Add-SPOContainerTypeBilling.md
> +If you don't have an Azure subscription, follow steps here to [create a subscription](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/initial-subscriptions
>https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/initial-subscriptions [](http://example.com/codeflow?start=86&length=113)

use relative link:

```
/azure/cloud-adoption-framework/ready/azure-best-practices/initial-subscriptions
```

2025-01-25 00:24 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Add-SPOContainerTypeBilling.md
> +Example 1 attaches the billing profile of Azure subscription ID “5a8a4d9f-9f8d-4cac-8a97-28ab04ff194c”, resource group “RG100” and region “(US) East US” to the container type ID “aa1d89b3-b4cf-4c0a-8
other places too

2025-01-25 00:27 UTC, samkabue commented
You also need to update the table of contents file `sharepoint-online.md`

2025-01-25 00:27 UTC, samkabue requested changes
:clock1:

2025-01-27 07:57 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the `<Paging Token>` provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the m
Yes. This is the exact string

2025-01-27 17:47 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +This parameter can be used when there are more than 200 Containers in a given SharePoint Embedded application. Using `-Paged` will provide a `<Paging Token>` that will display the next 200 Containers
other places too.

backticks are for "code" -- e.g., param names

2025-01-29 19:01 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45-as | ft
>- [](http://example.com/codeflow?start=46&length=1)

I'd suggest you use examples that don't have this dash `-` as it might confuse people as it looks like param `-as` at quick glance.

here and other places

2025-01-29 21:25 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the `<Paging Token>` provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the m
casing should match the actual backend string

2025-01-31 16:41 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45-as | ft
corrected

2025-01-31 18:06 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
> +{{Manually Enter Add-SPOContainerTypeBilling Description Here}}
>Manually Enter Add-SPOContainerTypeBilling Description Here [](http://example.com/codeflow?start=2&length=59)

set the actual description here

2025-01-31 18:07 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45 -Paged -PagingToken <Token String> | ft
><Token String> [](http://example.com/codeflow?start=67&length=14)

give a random example string

2025-01-31 18:07 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45 -Paged -PagingToken <Token String> | ft
do to all places you're passing "<Token String>" as the param value

2025-01-31 18:08 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Add-SPOContainerTypeBilling.md
> +Example 1 attaches the billing profile of Azure subscription ID "5a8a4d9f", resource group "RG100" and region "(US) East US" to the container type ID "aa1d89b3"
>89b3" [](http://example.com/codeflow?start=155&length=5)

this file and others:

end your sentences with `.` in all the example statements

2025-01-31 18:09 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
add `## RELATED LINKS` with links, similar to the other files

2025-01-31 18:09 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
> +{{Manually Enter Add-SPOContainerTypeBilling Description Here}}
same to your new entries below

2025-01-31 18:37 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
> +{{Manually Enter Add-SPOContainerTypeBilling Description Here}}
corrected

2025-01-31 18:42 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Get-SPOContainer -OwningApplicationId 423poi45 -Paged -PagingToken <Token String> | ft
corrected

2025-01-31 18:45 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/Add-SPOContainerTypeBilling.md
> +Example 1 attaches the billing profile of Azure subscription ID "5a8a4d9f", resource group "RG100" and region "(US) East US" to the container type ID "aa1d89b3"
corrected

2025-01-31 18:53 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
corrected

2025-01-31 19:10 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the `<Paging Token>` provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the m
I mean, remove the backticks, since this is not a param or code here. @ShreyasSar26

2025-01-31 19:11 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
add other related links, like you have for the other cmdlets in this PR

2025-01-31 19:13 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
> +{{Manually Enter Add-SPOContainerTypeBilling Description Here}}
Sentence should end with `.` @ShreyasSar26

2025-02-01 03:39 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
> +{{Manually Enter Add-SPOContainerTypeBilling Description Here}}
Corrected

2025-02-01 03:40 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the `<Paging Token>` provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the m
Corrected

2025-02-01 07:27 UTC, samkabue commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the paging token provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the messa
>commandlet [](http://example.com/codeflow?start=160&length=10)

`cmdlet`

here and elsewhere

2025-02-02 16:58 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the paging token provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the messa
corrected

2025-02-03 18:44 UTC, samkabue approved these changes
:shipit:

2025-02-04 04:06 UTC, ShreyasSar26 commented on sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
> +Use this parameter to provide the `<Paging Token>` provided to view the remaining Containers as shown in Example 4. If there are no more Containers to display, the commandlet output will return the m
Corrected

2025-02-04 18:53 UTC, merged