Update Set-SPOBuiltInSiteTemplateSettings.md
MicrosoftDocs/OfficeDocs-SharePoint-PowerShell pull request #82
Opened 2021-11-19 14:31 UTC by ansilv

Added missing Template IDs from Feature ID 85659 https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=85659

2021-11-19 14:32 UTC, opbld30 commented
Docs Build status updates of commit _[cc72268](https://github.com/ansilv/OfficeDocs-SharePoint-PowerShell/commits/cc72268204a79c9fcf3fc163108f6f5243ba9aa8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md](https://github.com/ansilv/OfficeDocs-SharePoint-PowerShell/blob/patch-2/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spobuiltinsitetemplatesettings?view=sharepoint-ps&branch=pr-en-us-82) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C19%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202111191431330836-82%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-20T14%3A32%3A46Z&sr=b&sp=r&sig=0kCQLvSja%2B2kXcUBDgyFondqOeeuEg3d3R7gJcUqlhg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 04:50 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md
> +| Retail Management     | e4ec393e-da09-4816-b6b2-195393656edd  |
```suggestion
| Retail Management     | e4ec393e-da09-4816-b6b2-195393656edd  | 
```
```suggestion
| Retail management     | e4ec393e-da09-4816-b6b2-195393656edd  | 
```

2021-11-22 04:50 UTC, JohanFreelancer9 commented on sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md
> +| Retail Management     | e4ec393e-da09-4816-b6b2-195393656edd  |
```suggestion
| Retail management     | e4ec393e-da09-4816-b6b2-195393656edd  | 
```

2021-11-22 04:51 UTC, JohanFreelancer9 requested changes
Copy review - @ansilv, kindly commit the suggested minor change. Many thanks.

2021-11-22 08:27 UTC, opbld30 commented
Docs Build status updates of commit _[4684039](https://github.com/ansilv/OfficeDocs-SharePoint-PowerShell/commits/4684039712a95ec0fab8b6aacbbe1c843ecc8602)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md](https://github.com/ansilv/OfficeDocs-SharePoint-PowerShell/blob/patch-2/sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/module/sharepoint-online/set-spobuiltinsitetemplatesettings?view=sharepoint-ps&branch=pr-en-us-82) (sharepoint-ps) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C22%5C3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d%5CPullRequest%5C202111220825269478-82%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-23T08%3A27%3A14Z&sr=b&sp=r&sig=HDJumOgRzGK2VQhQ5TxYmtF%2Fx7c%2F6sBwx8XRMGiPPf4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/3dbbfaea-2c18-2d63-2f2f-97a8fabaf65d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-22 14:40 UTC, JohanFreelancer9 approved these changes

2021-11-23 07:20 UTC, yogkumgit commented
@dariomws @tseward @get-itips

2021-11-23 08:32 UTC, dariomws approved these changes
For Healthcare and store collaboration, I'm receiving "This is not a valid site template ID" using PS module 16.0.21812.0. Will they appear in the next release?

2021-11-23 08:36 UTC, ansilv commented
> For Healthcare and store collaboration, I'm receiving "This is not a valid site template ID" using PS module 16.0.21812.0. Will they appear in the next release?

I think they are not in Production yet, at least they don't show in the templates for me. However, they should be released soon (?) and I got the IDs from the code, same place I got the retail management from: /odsp-next/apps/odsp-next/src/odsp-next/controls/webTemplatesGallery/components/WebTemplatesGalleryConstants.ts

https://onedrive.visualstudio.com/ODSP-Web/_git/odsp-web?path=/odsp-next/apps/odsp-next/src/odsp-next/controls/webTemplatesGallery/components/WebTemplatesGalleryConstants.ts&_a=contents&version=GBmain

2021-11-23 08:41 UTC, dariomws commented
Thanks @ansilv!

2021-11-23 13:38 UTC, tseward approved these changes

2021-11-24 12:32 UTC, yogkumgit commented
@get-itips

2021-11-24 12:34 UTC, get-itips approved these changes

2021-11-25 11:59 UTC, yogkumgit commented
@tiburd Please merge this PR. Thanks

2021-11-29 16:19 UTC, merged